### ISSUE TITLE
should generate .ensime if it does not exist

### ISSUE THREAD

**Issue by yazgoo** [ensime/ensime-vim#116]

**Comment by yazgoo** [comment]
Same problem as with ensime-launcher.
Plus the client has to be initialized, which requires .ensime.

**Comment by jvican** [comment]
Are you sure about this? I usually don't create a `.ensime` file to avoid using `ensime-vim` when editing. As the boot up of the server is slow, I will force the user to create that file with sbt if he's interested in using this plugin for that concrete project.
