### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by jarandaf** [ensime/ensime-vim#117]
Hi, I am getting the following errors:

````
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.netbeans.api#org-netbeans-api-java;RELEASE731: not found
[warn]  :: org.netbeans.api#org-netbeans-modules-java-source;RELEASE731: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.netbeans.api:org-netbeans-api-java:RELEASE731
[warn]            +- org.ensime:core_2.11:0.9.10-SNAPSHOT
[warn]            +- org.ensime:server_2.11:0.9.10-SNAPSHOT
[warn]            +- org.ensime:ensime_2.11:0.9.10-SNAPSHOT (/Users/jordi/.config/classpath_project_ensime/2.11.6/build.sbt#L12-18)
[warn]            +- default:root-2-11-6_2.11:0.1-SNAPSHOT
[warn]          org.netbeans.api:org-netbeans-modules-java-source:RELEASE731
[warn]            +- org.ensime:core_2.11:0.9.10-SNAPSHOT
[warn]            +- org.ensime:server_2.11:0.9.10-SNAPSHOT
[warn]            +- org.ensime:ensime_2.11:0.9.10-SNAPSHOT (/Users/jordi/.config/classpath_project_ensime/2.11.6/build.sbt#L12-18)
[warn]            +- default:root-2-11-6_2.11:0.1-SNAPSHOT
```

This has already been commented [here](https://github.com/ensime/ensime-server/issues/1126). Having a brief look, I think this might be fixed by adding such dependencies within the [build_sbt](https://github.com/ensime/ensime-vim/blob/master/ensime_launcher/__init__.py#L134) function, although I am not sure this is the proper solution (don't know anything about the project internals, so that would be possibly inappropriate).

**Comment by divarvel** [comment]
Same issue here.

**Comment by oschrenk** [comment]
I fixed this by adding
```
netbeans-releases: http://bits.netbeans.org/maven2
``` 

to `~/.sbt/repositories`.

**Comment by jvican** [comment]
Solved with @oschrenk comment. Works for me.

**Comment by jvican** [comment]
I think this is an sbt-related problem. Could we close this?

**Comment by Sciss** [comment]
I have the same issue. It's not good to ask the user to add a global resolver to their local sbt installation. Should be fixed in Ensime. Please re-open.

**Comment by jvican** [comment]
Sorry, I thought this was solved. This is a problem of dependencies that it's not related to `ensime-server` AFAIK. @fommil, do you know something about it? In any case, `ensime-vim` could do a small workaround but it's not the good place to do it and therefore I'm not convinced to implement it.

**Comment by Sciss** [comment]
I created this file: `~/sbt/0.13/netbeans.sbt` with contents:

    resolvers += "netbeans-releases" at "http://bits.netbeans.org/maven2"

Then the update worked.

**Comment by jvican** [comment]
Yes, that's how it's solved. But I would like to gather more information about why it happens.

**Comment by Sciss** [comment]
I think the update process from ensime must add that custom resolver to its sbt build file.

**Comment by rorygraves** [comment]
This is because of the newer java support in Ensime, the client needs to be updated the sbt project it generates to save the ensime classpath with the resolver - see the code here https://github.com/ensime/ensime-sublime/blob/master/server.py#L42 from the sublime plugin.

**Comment by rorygraves** [comment]
i.e. needs to be added here  - https://github.com/ensime/ensime-vim/blob/master/lib/start_ensime.sh

**Comment by jvican** [comment]
Sure @Sciss, I just wondered why it happened now and not before (previous releases).
  
Thanks @rorygraves, very useful as always.

**Comment by rorygraves** [comment]
No idea why it only just happened - the change has been in for a while.  Empty cache?

**Comment by jvican** [comment]
Maybe... the thing is that I applied this fix but then I removed it and checked that it was working (I believe I cleaned the cache but I must probably have forgotten). Submitting a PR for this.
