### ISSUE TITLE
Error detected while processing CursorHold Auto commands for "*.scala" in neovim

### ISSUE THREAD

**Issue by ajkaanbal** [ensime/ensime-vim#128]
Hi.

The error occurs after using `:EnDocBrowse`. The documentation opens correctly in the browser but nvim shows up the error message every time I tried to move the cursor, I have to reopen neovim. 

Error message:

```
Error detected while processing CursorHold Auto commands for "*.scala":
Invalid channel "1"
```

versions:
`$ nvim --version`
NVIM 0.1.1 (compiled Dec  9 2015 13:03:38)
`$ pip freeze | grep neovim`
neovim==0.0.38

init.vim

```
call plug#begin('~/.vim/bundle')
Plug 'ensime/ensime-vim'
call plug#end()
```

**Comment by ajkaanbal** [comment]
I found out what's happen

I set BROWSER=google-chrome when I change to BROWSER=firefox  it works, no more error message.

I modify this line:

https://github.com/ensime/ensime-vim/blob/master/rplugin/python/ensime.py#L303

to this: `subprocess.Popen([browser, url], stderr=subrocess.PIPE, stdout=subprocess.PIPE)`
 
And now is working also with google-chrome.

**Comment by vito-c** [comment]
https://github.com/ensime/ensime-vim/pull/130

**Comment by yazgoo** [comment]
Thanks @vito-c ,
Closing this, please re-open in case of problem.
