### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by yazgoo** [ensime/ensime-vim#136]

**Comment by jvican** [comment]
OK, I think it could be better if we only make tests for the neovim plugin (in python). It's really easy to embed a neovim instance and check functionality against a real instance of the editor. Vim won't be covered by the tests, but as all the logic of the plugin is in ensime_shared (which is shared by both vim and neovim) vim will indirectly be covered by the tests.
  
What do you think? More info [here](https://github.com/neovim/python-client).

**Comment by jvican** [comment]
Any feedback on this?

**Comment by ChrisCoffey** [comment]
How do you feel about using a Cucumber dialect like [Lettuce](http://lettuce.it/tutorial/simple.html#tutorial-simple) so we can share tests between emacs & vim? 

I'm pretty excited by the prospect and would love for our CI to work again, so I'm willing to take this on.

**Comment by jvican** [comment]
I think it's a great idea that I'd like to see implemented. I actually looked into this when Sam commented it, but I didn't see any feasible way of integrating it into `ensime-vim` in a clean way. If you can find it, please go ahead, this would be probably one of the best features of ensime-vim by far.

**Comment by jvican** [comment]
Hey @ChrisCoffey, just checking in, are you doing progress on the new test suite?

**Comment by ChrisCoffey** [comment]
I've been poking around with it, but was on vacation last week, so no real progress. At this point my plan is to chop this up into smaller tasks so folks can start picking them off.

**Comment by jvican** [comment]
That’s a great idea. Keep up the good work :smile:

**Comment by ches** [comment]
Okay, we've had the Lettuce suite set up for awhile, #327 added unit-level testing, and #312 proposes an implementation of embedded Neovim integration tests as @jvican suggested above. I think we can safely close this now 😄
