### ISSUE TITLE
Error Checking Issues

### ISSUE THREAD

**Issue by vito-c** [ensime/ensime-vim#139]
Issues with Error Type Checking:
- There is an ErrorStyle already available via the syntax `*Error          any erroneous construct` `:help syntax` line 258 that should be the default.
- The error highlighting shows up sometimes for me even when I don't run `EnTypeCheck` is error checking running via an autocommand? There should be a way to disable/enable this
- The error highlighting doesn't go away sometimes even when I run `EnTypeCheck` to try and clear the errors.

**Comment by jvican** [comment]
Are you still getting these errors @vito-c?

**Comment by vito-c** [comment]
I will test with latest but I am pretty sure I was still getting them

**Comment by jvican** [comment]
Any news @vito-c ?
