### ISSUE TITLE
Undefined variable: g:EnErrorStyle

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#141]
Hi there!
When I execute `:EnType` I am getting the following error:
```
Error detected while processing CursorHold Auto commands for "*.scala":
NVimError('Vim:E121: Undefined variable: g:EnErrorStyle'.)
```
Why and how can I solve it?
Thanks.

**Comment by jvican** [comment]
Solved with `:let EnErrorStyle='EnError'`. It would be handy to define it as the default one.

**Comment by vito-c** [comment]
Please leave this issue open. It's a valid bug fi the error style needs to be set
