### ISSUE TITLE
Request for Ensime refactorings (like variable/method renaming)?

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#143]
Hi guys,
  
I am interested in ensime's refactorings, specially variable/method renaming throughout a project. I think it's a must for `ensime-vim` to succeed in the scala world. I have a rough idea how to implement it in python via regex and search-and-replace mechanisms, without interacting with the ensime server.
  
However, it would be better to use the built-in refactoring features of ensime server. Any idea why this has not been implemented yet? Is it planned?
  
Other projects like `ensime-sublime` have some refactoring but not the one that I am requesting. Perhaps @rorygraves knows something.

BTW, happy new year.

**Comment by jvican** [comment]
I have already implemented the rename refactoring. Also, I am preparing a big PR with code refactorings and improvements, which will be available in the next days.

**Comment by rorygraves** [comment]
Great!  I'm not actually sure which ones sublime has, its certainly not even all the ones than ensime supports.

**Comment by jvican** [comment]
Yep! It's almost working but I have to propagate all the changes for vim as well, because the used python files are different.
  
Also, I am stuck with the renaming refactoring because of [this issue](https://github.com/ensime/ensime-server/issues/655). Unfortunately, this also affects other bits of ensime.
  
I will make this PR and mark it as WIP. When that issue is resolved in `ensime-server`, I will encourage @yazgoo to merge if everything looks good. In the meanwhile, I will be working on this but with special emphasis on `ensime-server`. Hope to solve some issues and fix some efficiency problems that Sam commented me.

**Comment by jvican** [comment]
Variable/method renaming included in #147. We'll open another issue to keep track of all the refactorings. Closing this.
