### ISSUE TITLE
:EnType does not display input/output type of function

### ISSUE THREAD

**Issue by dubiousdavid** [ensime/ensime-vim#146]
```println("Hello World!")```
Cursour around the letter 'p' displays nothing.
Cursor around the letter 'n' displays `scala.Unit`.

I would hope for something like I see in the doc uri, `println(x:Any):Unit`.

**Comment by jvican** [comment]
My last PR (https://github.com/ensime/ensime-vim/pull/147) fixes this. Wait some days until it's merged!
