### ISSUE TITLE
move docs/readme to ensime.org

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-vim#148]
we are trying to consolidate all docs. Please move your README to http://ensime.github.io/editors/vim/ and follow the README convention e.g. https://raw.githubusercontent.com/ensime/ensime-server/master/README.md

the other half of https://github.com/ensime/ensime.github.io/issues/10

**Comment by fommil** [comment]
ping

**Comment by ChrisCoffey** [comment]
I should be able to take care of this tonight after NE Scala ends.

**Comment by ChrisCoffey** [comment]
@jvican @fommil Do you guys want have the ensime-vim readme point to [ensime.github.io](https://ensime.github.io) like the ensime-emacs project does? If not, this can be closed.

**Comment by fommil** [comment]
Definitely redirecting! Consolidating the docs is the key.

**Comment by jvican** [comment]
Closed by #176.
