### ISSUE TITLE
Python exception not caught

### ISSUE THREAD

**Issue by Kazy** [ensime/ensime-vim#165]
Quite often a Python exception is not caught and is instead displayed in Vim, making it unusable. It's the same exception every time.

While it is not the only way to obtain it (it sometime happens randomly), I found that I can reproduce it every time with the following steps:

* Clone https://github.com/heathermiller/f-p
* Open `core/src/main/scala/RDD.scala`, and wait for Ensime to initialize
* Go line 31, on the takeAllSync function name, and call `:EnType`. A few second latter, exception.

Only tested with Neovim. This is the traceback: http://pastebin.com/hNGGDKz6. Here is `ensime-vim.log` http://pastebin.com/kcb9yPck, and `server.log` http://pastebin.com/kmenxb8Z.

**Comment by jvican** [comment]
Thanks for the report Jocelyn :smile: I'll look into it soon!

**Comment by jvican** [comment]
Similar to #164.
