### ISSUE TITLE
Execute :EnClasspath to set a classpath (on master)

### ISSUE THREAD

**Issue by casertap** [ensime/ensime-vim#168]
When I open a .scala file in vim, I get the bip sound at regular interval and I get the message:
Execute :EnClasspath to set a classpath
my .ensime looks like this (ignore the line numbers, lines are truncated (>) at the end because I could not do a proper copy paste from the vim of my docker machine):
```
1 (
  2  :root-dir "/code/scala-sbt-template"
  3  :cache-dir "/code/scala-sbt-template/.ensime_cache"
  4  :scala-compiler-jars ("/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.3.jar" "/root/.ivy2/cache/org.scala-lang/scala-library/jars/sca>
  5  :name "scala-sbt-template"
  6  :java-home "/usr/lib/jvm/java-7-openjdk-amd64"
  7  :java-flags ("-Xss2m" "-Xms1024m" "-Xmx1024m" "-XX:ReservedCodeCacheSize=128m" "-XX:MaxPermSize=256m")
  8  :reference-source-roots nil
  9  :scala-version "2.10.3"
 10  :compiler-args ("-unchecked" "-deprecation" "-feature" "-Xlint" "-Yinline-warnings" "-Yno-adapted-args" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture")
 11  :formatting-prefs nil
 12  :disable-source-monitoring nil
 13  :disable-class-monitoring nil
 14  :subprojects ((
 15    :name "scala-sbt-template"
 16    :source-roots ("/code/scala-sbt-template/src/main/scala" "/code/scala-sbt-template/src/test/scala")
 17    :targets ("/code/scala-sbt-template/target/scala-2.10/classes")
 18    :test-targets ("/code/scala-sbt-template/target/scala-2.10/test-classes")
 19    :depends-on-modules nil
 20    :compile-deps ("/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.3.jar")
 21    :runtime-deps nil
 22    :test-deps ("/root/.ivy2/cache/org.ow2.asm/asm/jars/asm-4.1.jar" "/root/.ivy2/cache/org.ow2.asm/asm-analysis/jars/asm-analysis-4.1.jar" "/root/.ivy2/cache/or>
 23    :doc-jars ("/root/.ivy2/cache/org.ow2.asm/asm/docs/asm-4.1-javadoc.jar" "/root/.ivy2/cache/org.ow2.asm/asm-analysis/docs/asm-analysis-4.1-javadoc.jar" "/root>
 24    :reference-source-roots ("/root/.ivy2/cache/org.ow2.asm/asm/srcs/asm-4.1-sources.jar" "/root/.ivy2/cache/org.ow2.asm/asm-analysis/srcs/asm-analysis-4.1-sourc>
 25 )
```

I am using the last version on the master branch.
After having this error, my vim will freeze when I quit vim.

I got no answer commenting on this ticket: https://github.com/ensime/ensime-vim/issues/150

**Comment by jvican** [comment]
Hi @casertap, sorry but I cannot solve this ATM because I'm under two deadlines. Is there anyone in the community that can take a look at this?

**Comment by ajkaanbal** [comment]
Hi @casertap.  remove .config/ensime-vim and also .ensime and .ensime_cache located in your project folder and try again. 

About the bip sound, maybe you need to add this: `set noerrorbells`

**Comment by ches** [comment]
I had similar symptoms. My first run of `:EnClasspath` succeeded, messages from ensime-vim indicated it was analyzing, etc. and the ensime server started. Then my first attempt to use anything, executing `:EnType`, made things go sideways—tmux telling me there were error bells in the terminal every second or so (visual bells setting enabled) and Vim becoming sluggish with whatever was repeatedly causing errors, and finally hanging on `:q` requiring a `kill -9` to end the process, like @casertap's report.

My `.ensime` in this project was originally generated by the Ensime SBT plugin and used successfully with `ensime-atom`, so I tried `rm -rf .ensime .ensime_cache`. Now `:EnClasspath` in Vim for this project does nothing: no output, no `.ensime` file generated.

I guess I'll try nuking `~/.config/ensime-vim` next when I can spend more time fiddling with it, but could ensime-vim possibly promote using one of the build tool plugins like ensime-sbt explicitly—like the editor plugins for Emacs, Atom, etc. do—instead of abstracting lots of magic behind `:EnClasspath` and an SBT project hidden away in `~/.config`? I'll try to lend a hand or more informed feedback when I have more time to read ensime-vim's implementation.

**Comment by jvican** [comment]
Hi @ches, that is probably a very good idea. There are a lot of problems with the generation of the classpath from the vim editor, mostly because sbt is interactive and we have to execute it in another process and wait until it's finished. This is a very clunky process and sometimes it fails. Contributions are welcome, so if you want to play around with it go ahead :+1:

**Comment by jvican** [comment]
Have you solved the issue @ches? Any feedback?

**Comment by casertap** [comment]
I was using iTerm and tmux the first time. 
I tried again this morning using Terminall.app alone and I get the same result.

**Comment by jvican** [comment]
Yes, unfortunately it's supposed to fail. We've been having that issue for ages. I'll try to solve it soon.
  
We've been doing some changes to the queue/unqueue logic (the guy responsible of this issue). It'd be awesome if you could try it with the latest version from upstream.

**Comment by casertap** [comment]
Yes here is the detail of what I get from my test I just did now on master

```
root@3fc40c8b164f:/code/my/playing-with-actors# ls -al          
total 4
drwxr-xr-x 1 1000 staff 204 Mar  8 22:04 .          
drwxr-xr-x 1 1000 staff 170 Feb 29 11:57 ..         
-rwxr-xr-x 1 1000 staff 152 Feb  1 03:36 build.sbt  
drwxr-xr-x 1 1000 staff 102 Feb 29 12:03 project    
drwxr-xr-x 1 1000 staff 102 Feb  1 03:36 src        
drwxr-xr-x 1 1000 staff 204 Mar  1 22:05 target     
root@3fc40c8b164f:/code/my/playing-with-actors# sbt gen-ensime  
Getting org.scala-sbt sbt 0.13.11 ... 
:: retrieving :: org.scala-sbt#boot-app             
        confs: [default]         
        49 artifacts copied, 0 already retrieved (17330kB/290ms)
Getting Scala 2.10.6 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala           
        confs: [default]         
        5 artifacts copied, 0 already retrieved (24494kB/145ms) 
[info] Loading global plugins from /root/.sbt/0.13/plugins      
[info] Updating {file:/root/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ... 
[info] Done updating.
[info] Set current project to Playing with Actors (in build file:/code/my/playing-with-actors/)
[info] ENSIME update. Please vote for https://github.com/sbt/sbt/issues/2266       
[info] ENSIME updateClassifiers. Please vote for https://github.com/sbt/sbt/issues/1930        
[info] Resolving org.scala-lang#scalap;2.11.7 ...   
[info] ENSIME processing playing-with-actors (Playing with Actors)   
[warn] No Java sources detected in /usr/lib/jvm/java-8-openjdk-amd64 (your ENSIME experience will not be as good as it could be.)  
[warn] Some source directories do not exist and will be ignored by ENSIME.         
[warn] For example: /code/my/playing-with-actors/src/test/scala
root@3fc40c8b164f:/code/my/playing-with-actors# ls -al   
total 8       
drwxr-xr-x 1 1000 staff  238 Mar  9 00:29 .         
drwxr-xr-x 1 1000 staff  170 Feb 29 11:57 ..        
-rw-r--r-- 1 1000 staff 1980 Mar  9 00:29 .ensime   
-rwxr-xr-x 1 1000 staff  152 Feb  1 03:36 build.sbt 
drwxr-xr-x 1 1000 staff  102 Feb 29 12:03 project   
drwxr-xr-x 1 1000 staff  102 Feb  1 03:36 src       
drwxr-xr-x 1 1000 staff  204 Mar  1 22:05 target

root@3fc40c8b164f:/code/my/playing-with-actors# vim    
```
I start vim and run :EnClasspath
I get this
```
Getting org.scala-sbt sbt 0.13.8 ...      
:: retrieving :: org.scala-sbt#boot-app   
        confs: [default]    
        52 artifacts copied, 0 already retrieved (17674kB/299ms)      
Getting Scala 2.10.4 (for sbt)...         
:: retrieving :: org.scala-sbt#boot-scala 
        confs: [default]    
        5 artifacts copied, 0 already retrieved (24459kB/137ms)       
[info] Loading global plugins from /root/.sbt/0.13/plugins            
[info] Updating {file:/root/.sbt/0.13/plugins/}global-plugins...      
[info] Resolving org.ensime#ensime-sbt;0.4.0 ...        
[info] Resolving org.scala-lang#scalap;2.10.6 ...       
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...             
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scalariform#scalariform_2.10;0.1.4 ...           
[info] Resolving org.scala-sbt#sbt;0.13.8 ...           
[info] Resolving org.scala-sbt#main;0.13.8 ...          
[info] Resolving org.scala-sbt#actions;0.13.8 ...       
[info] Resolving org.scala-sbt#classpath;0.13.8 ...     
[info] Resolving org.scala-sbt#launcher-interface;0.13.8 ...          
[info] Resolving org.scala-sbt#interface;0.13.8 ...     
[info] Resolving org.scala-sbt#io;0.13.8 ...            
[info] Resolving org.scala-sbt#control;0.13.8 ...       
[info] Resolving org.scala-sbt#completion;0.13.8 ...    
[info] Resolving org.scala-sbt#collections;0.13.8 ...   
[info] Resolving jline#jline;2.11 ...     
[info] Resolving org.scala-sbt#api;0.13.8 ...           
[info] Resolving org.scala-sbt#compiler-integration;0.13.8 ...        
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...        
[info] Resolving org.scala-sbt#logging;0.13.8 ...       
[info] Resolving org.scala-sbt#process;0.13.8 ...       
[info] Resolving org.scala-sbt#relation;0.13.8 ...      
[info] Resolving org.scala-sbt#compile;0.13.8 ...       
[info] Resolving org.scala-sbt#classfile;0.13.8 ...     
[info] Resolving org.scala-sbt#persist;0.13.8 ...       
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...       
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...    
[info] Resolving org.scala-sbt#ivy;0.13.8 ...           
[info] Resolving org.scala-sbt#cross;0.13.8 ...         
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...     
[info] Resolving com.jcraft#jsch;0.1.46 ...             
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...           
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...           
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ... 
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...  
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...         
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...            
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...         
[info] Resolving org.scala-sbt#run;0.13.8 ...           
[info] Resolving org.scala-sbt#task-system;0.13.8 ...   
[info] Resolving org.scala-sbt#tasks;0.13.8 ...         
[info] Resolving org.scala-sbt#tracking;0.13.8 ...      
[info] Resolving org.scala-sbt#cache;0.13.8 ...         
[info] Resolving org.scala-sbt#testing;0.13.8 ...       
[info] Resolving org.scala-sbt#test-agent;0.13.8 ...    
[info] Resolving org.scala-sbt#test-interface;1.0 ...   
[info] Resolving org.scala-sbt#main-settings;0.13.8 ... 
[info] Resolving org.scala-sbt#apply-macro;0.13.8 ...   
[info] Resolving org.scala-sbt#command;0.13.8 ...       
[info] Resolving org.scala-sbt#logic;0.13.8 ...

[info] Resolving org.scala-sbt#compiler-interface;0.13.8 ...         NAMES
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...           8712aa432447        9dce9be12f14        "/bin/bash"         About a minute ago   Up About a minute   0.0.0.0:
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...           8080->8080/tcp, 0.0.0.0:8888->8888/tcp   elated_galileo
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...           tocs-MacBook-Pro-3:scala pierrecaserta$ docker stop 8712aa432447
[info] Resolving org.scala-lang#jline;2.10.4 ...        tocs-MacBook-Pro-3:scala pierrecaserta$
[info] Resolving org.fusesource.jansi#jansi;1.4 ...     tocs-MacBook-Pro-3:scala pierrecaserta$ -
[info] Done updating.       
[info] Loading project definition from /root/.config/ensime-vim/2.11.7/project      
[info] Updating {file:/root/.config/ensime-vim/2.11.7/project/}root-2-11-7-build... 
[info] Resolving org.scala-sbt#global-plugins;0.0 ...   
[info] Resolving org.ensime#ensime-sbt;0.4.0 ...        
[info] Resolving org.scala-lang#scalap;2.10.6 ...       
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...             
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scalariform#scalariform_2.10;0.1.4 ...           
[info] Resolving org.scala-sbt#sbt;0.13.8 ...           
[info] Resolving org.scala-sbt#main;0.13.8 ...          
[info] Resolving org.scala-sbt#actions;0.13.8 ...       
[info] Resolving org.scala-sbt#classpath;0.13.8 ...     
[info] Resolving org.scala-sbt#launcher-interface;0.13.8 ...          
[info] Resolving org.scala-sbt#interface;0.13.8 ...     
[info] Resolving org.scala-sbt#io;0.13.8 ...            
[info] Resolving org.scala-sbt#control;0.13.8 ...       
[info] Resolving org.scala-sbt#completion;0.13.8 ...    
[info] Resolving org.scala-sbt#collections;0.13.8 ...   
[info] Resolving jline#jline;2.11 ...     
[info] Resolving org.scala-sbt#api;0.13.8 ...           
[info] Resolving org.scala-sbt#compiler-integration;0.13.8 ...        
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...        
[info] Resolving org.scala-sbt#logging;0.13.8 ...       
[info] Resolving org.scala-sbt#process;0.13.8 ...       
[info] Resolving org.scala-sbt#relation;0.13.8 ...      
[info] Resolving org.scala-sbt#compile;0.13.8 ...       
[info] Resolving org.scala-sbt#classfile;0.13.8 ...     
[info] Resolving org.scala-sbt#persist;0.13.8 ...       
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...       
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...    
[info] Resolving org.scala-sbt#ivy;0.13.8 ...           
[info] Resolving org.scala-sbt#cross;0.13.8 ...         
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...     
[info] Resolving com.jcraft#jsch;0.1.46 ...             
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...           
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...           
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ... 
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...  
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...         
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...            
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...         
[info] Resolving org.scala-sbt#run;0.13.8 ...           
[info] Resolving org.scala-sbt#task-system;0.13.8 ...   
[info] Resolving org.scala-sbt#tasks;0.13.8 ...         
[info] Resolving org.scala-sbt#tracking;0.13.8 ...      
[info] Resolving org.scala-sbt#cache;0.13.8 ...         
[info] Resolving org.scala-sbt#testing;0.13.8 ...       
[info] Resolving org.scala-sbt#test-agent;0.13.8 ...    
[info] Resolving org.scala-sbt#test-interface;1.0 ...   
[info] Resolving org.scala-sbt#main-settings;0.13.8 ... 
[info] Resolving org.scala-sbt#apply-macro;0.13.8 ...   
[info] Resolving org.scala-sbt#command;0.13.8 ...       
[info] Resolving org.scala-sbt#logic;0.13.8 ...         
[info] Resolving org.scala-sbt#compiler-interface;0.13.8 ...          
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...           
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...           
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...           
[info] Resolving org.scala-lang#jline;2.10.4 ...        
[info] Resolving org.fusesource.jansi#jansi;1.4 ...     
[info] Resolving org.scala-lang#scalap;2.10.4 ...       
[info] Done updating.       
[info] Set current project to root-2-11-7 (in build file:/root/.config/ensime-vim/2.11.7/)        
[info] Updating {file:/root/.config/ensime-vim/2.11.7/}root-2-11-7...
````
I missed 3 lines of logs sorry.

Then I am back to vim. I see no improvement from envime-sim and my vim is stuck I can not quit using :q I need to shutdown the machine.

**Comment by casertap** [comment]
I quickly pushed my source code on github: https://github.com/casertap/playing-with-actors

my config is pretty simple: I added this to: /root/.sbt/0.13/plugins/plugins.sbt
```
resolvers += Resolver.sonatypeRepo("snapshots")

addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.0")
```

**Comment by jvican** [comment]
Thanks for all the info! This would look like a very straightforward fix that we need to do on the vim side of the plugin. I'll look into it.

**Comment by casertap** [comment]
Just in case you are interested (if it can help)
Here are the command to use Docker and simulate my exact same environment.
You need to use my playing-with-akka repository

```
cd my/playing-with-actors/
docker-machine create --driver virtualbox scala-vim
eval "$(docker-machine env scala-vim)"
docker build -t test/scala-vim-image:latest .
docker run --name scala-vim-container -it --entrypoint=/bin/bash -v /Users/pierrecaserta/workspace/scala/my/playing-with-actors:/code/ test/scala-vim-image
```
INSIDE THE CONTAINER (/code)
```
rm .ensime
rm -rf .ensime_cache/
sbt gen-ensime
vim
```
At this point you should experience the same problem as me.
Remember that the first time you are using sbt, it feel like it freeze but you actually need to wait (a lot).

To avoid this each time I am running the container I am saving the .ivy2 on the host and share it in my container when I "docker run"
```
-v /Users/pierrecaserta/workspace/scala/my/playing-with-actors/.ivy2:/root/.ivy2
```

**Comment by casertap** [comment]
Damn! Rebuilding the images made me realize few things:
ensime-sbt needs scala 2.10
akka 2.4.0 needs scala 2.12

Ok I am changing in build.sbt
```
scalaVersion := "2.10.6"
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.3.14")
```

I realize the ensime-sbt snapshots have been renamed:
https://oss.sonatype.org/content/repositories/snapshots/org/ensime/ensime-sbt_2.10_0.13/

in /root/.sbt/0.13/plugins/plugins.sbt I change the version:
```
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.4.1-SNAPSHOT")
```

But I the end the bug persist.
I updated my Dockerfile and my configs and code on my repo: https://github.com/casertap/playing-with-actors

**Comment by casertap** [comment]
So after retrograding all the versions and build the .ensime again, run the :EnClasspath it worked fine...

In my project, I want to use the last version of akka (make use of java 8 closure and needs scala 2.11).
The very recent version of scala (2.12) also made tremendous progress and use java 8 as well.
Is that possible to work on updating ensime-vim with more recent versions of scala?

**Comment by jvican** [comment]
Hey @casertap, really glad to hear that!
  
We don't embed any scala version, the guy doing that is `ensime-server` so you could go there to ask. However, the very recent version of scala still doesn't have all the libraries in maven and that's gonna take a while...

**Comment by jvican** [comment]
As you've already solved this problem, I'm gonna close this. Feel free to comment, though.

**Comment by ches** [comment]
> We don't embed any scala version, the guy doing that is ensime-server so you could go there to ask.

The classpath generation does [create an internal sbt project tied to a Scala version][1]. Since this evidently can lead to issues (and is a bit of a cumbersome approach), I'd propose removing it as I mentioned above. I haven't had a chance to work with ensime-vim since my earlier comment but I'll try to whip up a pull request, I think I have some time.

[1]: https://github.com/ensime/ensime-vim/blob/db5ae22287867fe0a3f92c6f1db4cbd7fd74e80c/ensime_shared/launcher.py#L180

**Comment by jvican** [comment]
Sorry, but that's a misunderstanding. We don't embed that scala version, that scala version is embedded by the plugin ensime-sbt that creates all the bootstrapping for ensime-vim. You already install it, since it's a requirement for the vim plugin to work. That is generating only the task that sbt will detect and execute afterwards. We're just following the standard recommended way to generate the classpath, which I believe other text editors are also following.

**Comment by jvican** [comment]
If what you're proposing is to defer the the classpath generation to the particular buiild tools, I'm up for it, that'd remove a lot of boilerplate-y code that we have only to handle that feature. And also, sometimes it's quite buggy.

**Comment by ches** [comment]
Yes sorry @jvican, I didn't mean to imply that ensime-vim was "embedding" any specific Scala version, just that its strategy of generating a hidden `built.sbt` to bootstrap the ensime server could possibly lead to confusion on this point. Like if Scala 2.10.x was the default on @casertap's `PATH` or in a project sbt config when he first started out (so ensime-sbt put that version in `.ensime` and thus it ended up also in the bootstrap `build.sbt` generated by ensime-vim), but then he changed his project to a different Scala version, maybe something went wrong in that scenario that isn't being handled? In the original issue above `.ensime` indeed contained `:scala-version "2.10.3"`, though @casertap's later output seemed to indicate ensime-vim successfully bootstrapping for Scala 2.11.7 so maybe the switch was smooth after all.

Anyway, let's explore some alternatives and see how that goes :smile:  I know there are more pieces to figure out other than just the `.ensime` generation that the build tool plugins can do.

**Comment by ches** [comment]
Btw @casertap the Scala version used to *build* sbt and its plugins like ensime-sbt does not limit the version used by your projects and dependencies—sbt will resolve plugins for its version and then use whatever compiler version you've set to build your project. I can't tell above what issues you were having with version differences but perhaps there was a red herring?

**Comment by ches** [comment]
So, I've just gotten the chance to start from scratch, and I'm still finding the same behavior that @casertap has reported in the course of this ticket: at this point, everything is technically working for me (e.g. I can start the ensime server with `:EnClasspath` and get some valid query responses like from `:EnType`), but the error bell is being triggered every second and Vim is unusably slow. With console Vim I have to `kill -9` to quit it.

I'm using MacVim 7.4.1655, same behavior running in GUI or console. ensime-vim 53867caaf90a48b891 (HEAD of master as of now), and I just now did the following to reset:

- `rm -rf ~/.config/ensime-vim`
- `rm -rf .ensime*` in my project
- `rm -rf ~/.ivy2/cache/org.ensime`
- `sbt gen-ensime` anew
- `:EnClasspath`, server successfully started as noted above

I'm not too familiar with working on Python Vim plugins—any pointers for how to start debugging this, getting some verbose output?

**Comment by ChrisCoffey** [comment]
I'm going to reopen this since it sounds like @casertap 's error bell never fully stopped. If this turns out to be a distinct issue I'll re-close this and open a new ticket.

@ches can you attach your server.log & ensime-vim.log files or put their tails in a gist?

**Comment by ches** [comment]
Ah, just realized that `ensime-vim.log` exists, we should perhaps mention this in the issue template and troubleshooting docs 😄 

Here are my logs and `.ensime`: https://gist.github.com/ches/9af6c5173205f03335a31ae5916b3339

**Comment by ChrisCoffey** [comment]
great, I'll take a look at this tonight when I get home

**Comment by jasonij** [comment]
Okay, I've been lurking on this one because I too have the bell bell bell problem (on neovim).

**Comment by ChrisCoffey** [comment]
I suspect, but am not positive that #218 will address this.

**Comment by jvican** [comment]
Yes, positive, #218 addresses this.
