### ISSUE TITLE
complete_func does not work

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#169]
I'm running `NVIM 0.1.2` with `+acl   +iconv    +jemalloc` with python 2.7.

Omni-completion appears to be broken on NeoVim in the current version. `fun_en_complete_func` in `ensime_shared.py` is dropping into the vim use-case, which in turn fails to call `complete()`. I played around with flipping the `if not base` condition, but it didn't seem to make a difference. 

Here's the log:
```
'lazy_initialize_ensime', ['                self.log(str(inspect.stack()))\n'], 0), (<frame object at 0x102c30638>, '/Users/ccoffey/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py', 178, 'setup', ['        return lazy_initialize_ensime() and ready_to_connect()\n'], 0), (<frame object at 0x102c7c450>, '/Users/ccoffey/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py', 910, 'client_for', ['            if client.setup(quiet=quiet, create_classpath=create_classpath):\n'], 0), (<frame object at 0x1019007a0>, '/Users/ccoffey/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py', 886, 'current_client', ['                create_client=create_client)\n'], 0), (<frame object at 0x101900580>, '/Users/ccoffey/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py', 837, 'wrapper2', ['                create_client=create_client)\n'], 0), (<frame object at 0x1028a4410>, '/Users/ccoffey/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py', 130, 'au_buf_enter', ['        super(NeovimEnsime, self).au_buf_enter(*args, **kwargs)\n'], 0), (<frame object at 0x102889c20>, '/Users/ccoffey/anaconda/lib/python2.7/site-packages/neovim/plugin/host.py', 65, '_on_request', ['        rv = handler(*args)\n'], 0), (<frame object at 0x1006d5ba0>, '/Users/ccoffey/anaconda/lib/python2.7/site-packages/neovim/api/common.py', 237, 'filter_request_cb', ["                                walk(self._in, args, self, name, 'request'))\n"], 0), (<frame object at 0x102c7c250>, '/Users/ccoffey/anaconda/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py', 177, 'handler', ['                rv = self._request_cb(name, args)\n'], 0)]
2016-02-27 16:26:42.996414: setup(True, False) called by wrapper2()
2016-02-27 16:26:43.007606: send_request: in
2016-02-27 16:26:43.007772: send: in
2016-02-27 16:26:43.007884: send: {"callId": 0, "req": {"typehint": "ConnectionInfoReq"}}
2016-02-27 16:26:44.578689: unqueue: result received {
  "callId": 0,
  "payload": {
    "typehint": "ConnectionInfo",
    "implementation": {
      "name": "ENSIME"
    },
    "version": "0.8.19"
  }
}
2016-02-27 16:26:44.578921: handle_incoming_response: in {u'implementation': {u'name': u'ENSIME'}, u'typehint': u'ConnectionInfo', u'version': u'0.8.19'}
2016-02-27 16:26:44.579794: Response {u'implementation': {u'name': u'ENSIME'}, u'typehint': u'ConnectionInfo', u'version': u'0.8.19'} has not been handled
2016-02-27 16:26:46.602162: ['1', ''] None
2016-02-27 16:26:46.602325: complete_func: in ['1', ''] None
2016-02-27 16:26:46.607227: [0, '        request.'] None
2016-02-27 16:26:46.607324: complete_func: in [0, '        request.'] None
```

I'm happy to look into this more, but I could use a bit of advice on where to look.

**Comment by jvican** [comment]
Hi @ChrisCoffey, basically the trick to do the omnicompletion is to call the server as soon as possible (in the first call) and then, when vim calls with a `0`, it waits for the response if it still hasn't arrived.
  
However I agree that most of the times it doesn't work (and I have to dig into this more deeply, but I don't have time). Apparently, when you call it several times it does work, maybe because there is a race condition there.
  
All the logic is in here: https://github.com/ensime/ensime-vim/blob/master/ensime_shared/ensime.py#L787. If you could look into this it would be awesome. I think that the trick I tell you in #170, could solve it.

**Comment by ChrisCoffey** [comment]
What I was referring to in this situation is actually that the condition at https://github.com/ensime/ensime-vim/blob/master/ensime_shared/ensime.py#L802 simply does not work in NeoVim. The log above shows that `findstart` is a list with two elements, rather than just the bit expected.

**Comment by jvican** [comment]
Oh, you are completely right, I didn't know neovim changed that. It's supposed to be `1` in vim. Could you please submit a PR to fix this as well?

**Comment by jvican** [comment]
Wait, no, actually I remember this. Yes, your last PR fixes this. I did the logic for vim/neovim out of `complete_func`. Thanks!
