### ISSUE TITLE
Support Public Symbol Searching

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#174]
Often times I find that I want to look up a particular function or type by name (or at least the part of the name I remember) but I usually fall back on grep or ctags. I've been playing around with ENSIME's public symbol search and it seems to fit what I'm looking for. 

The only question I have left before pushing my changes for you guys to review is whether the results should go into the quickfix window or a side buffer. Do either @jvican or @yazgoo have a preference?

**Comment by ches** [comment]
I'd like this feature too, the Atom ensime plugin implements it IIRC, with
a pop-up palette. I'd vote for quickfix window—if it's possible (now or in
the future) to scope the search to a single file then location list could
be used in that case and it will be nice and uniform.

It would also be nice if ensime-vim exposed this as an API that could be
hooked/called by Unite, CtrlP, etc.

>

**Comment by jvican** [comment]
I see this feature in a quickfix window :smile:

**Comment by ChrisCoffey** [comment]
@jvican ready for you to take a look. 

I did not expose it as an API, although I'm more than happy to do that in the future.

**Comment by jvican** [comment]
Let's leave the public API for the future because it's something that it affects quite a lot of features of `ensime-vim`.
