### ISSUE TITLE
SuggestImport shuts down vim if you don't select any suggestion

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#188]
When I  type `EnSuggestImport` and a list of suggestions appear, if I don't want any of those and I cancel (press <ENTER>), vim shuts down.
  
Do you know something about this @kstep?

**Comment by kstep** [comment]
Hmm. Never met such behavior. I use all my patches in production on quite large Scala project (about 800Ksloc) and never managed to crash it.

I use neovim, but also tried vim as well to verify the bug, and no, I can not reproduce it.
I tried pressing `Enter`, `Esc`, `0`. No matter what, both neovim and vim doesn't crash.

**Comment by kstep** [comment]
Could you please provide some more info? Maybe an example of Scala code it is crashed on, maybe backtrace (if available), what symbol you are trying to get suggestion for.

**Comment by jvican** [comment]
Sure, I didn't provide more info since I haven't got much time lately and at that moment I was quite pressured. I'll do that in the next days.

**Comment by jvican** [comment]
Disappeared, closing...
