### ISSUE TITLE
Package Inspector

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#190]
It looks like ENSIME & the Emacs plugin have support for displaying an outline of a package's contents. Is this something we want to bother porting to ENSIME-Vim, or are we happy enough with ctags and other outlining options? I could go either way on this.

**Comment by jvican** [comment]
I think it's good if we don't rely on ctags for this and we do port it to ensime-vim :+1:

**Comment by ChrisCoffey** [comment]
Works for me. I'm thinking the output should write to a narrow vertical buffer, similar to nerd tree. Does that sound reasonable to you @jvican?

**Comment by jvican** [comment]
Perfectly reasonable @ChrisCoffey!
