### ISSUE TITLE
Interested in seeing all the possible method signatures at typing time

### ISSUE THREAD

**Issue by casertap** [ensime/ensime-vim#192]
Hi guys,
I enjoy ensime-vim, very good work, thank you so much.

Is it possible to see all the possible method signatures at typing time?
For instance in the screenshot bellow I have the declaration on top and actorOf method has 2 signature:
```
actorOf(props: Props): ActorRef
actorOf(props: Props, name: String): ActorRef
```
in the buffer below I am creating a new actor using: system.actorOf...

![declaration](https://cloud.githubusercontent.com/assets/284394/13762333/5e33aaaa-ea92-11e5-8a47-99d4e40906f4.jpg)

At this point, I would like to see all the possible signatues.
Is this possible?

**Comment by ChrisCoffey** [comment]
You can use the omni complete list, <C-x><C-o>, which pulls in what you
want.

**Comment by casertap** [comment]
this is what I get by doing that:
![error](https://cloud.githubusercontent.com/assets/284394/13762668/9ae037dc-ea94-11e5-8bcf-b343670a7dfe.jpg)

**Comment by ChrisCoffey** [comment]
Yikes. Can you link to the repo causing the issue? Also it would be helpful
if you can attach you server and ensime-vim logs. I'll take a look tonight.

**Comment by casertap** [comment]
This is what is generated inside the ensime-vim.log
```
1457 2016-03-14 23:25:54.872751: 1.
1458 2016-03-14 23:25:54.873687: complete_func: in 1.
1459 2016-03-14 23:25:54.883299: complete: in
1460 2016-03-14 23:25:54.884252: 74 23
1461 2016-03-14 23:25:54.885065: 2021
1462 2016-03-14 23:25:54.885603: path: in
1463 2016-03-14 23:25:54.886156: send_request: in
1464 2016-03-14 23:25:54.886730: send: in
1465 2016-03-14 23:25:54.887448: send: {"callId": 18, "req": {"typehint": "CompletionsReq", "point": 2021, "caseSens": true, "maxResults": 100, "reload": false, "fileInfo": {"contents": "package com.packt.akka\n\nimport com.packt.akka.User\nimport scala.language.postfixOps\nimport akka.pattern.>
1466 2016-03-14 23:25:54.918334: 0 actorO
```
in server.log

```
205 23:27:29.394 DEBUG akka://ENSIME/user/$a/19 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/code/my/playing-with-actors2/src/main/scala/TalkToActor.scala,Some(...),None),2021,100,true,false)
206 23:27:29.394 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/code/my/playing-with-actors2/src/main/scala/TalkToActor.scala,Some(...),None),2021,100,true,false) in state handleRequests
207 23:27:29.395 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/code/my/playing-with-actors2/src/main/scala/TalkToActor.scala,Some(...),None),2021,100,true,false) in state ready
208 23:27:29.448 DEBUG None o.e.c.RichPresentationCompiler - Completing at tree:Select(Select(This(object App), system), actorO)
209 23:27:29.457 INFO  None o.e.c.RichPresentationCompiler - Found 69 members.
210 23:27:29.459 INFO  None o.e.c.RichPresentationCompiler - Filtered down to 2.
211 23:27:29.462 DEBUG akka://ENSIME/user/$a/19 o.e.s.RequestHandler - received handled message CompletionInfoList(actorO,List(CompletionInfo(actorOf,CompletionSignature(List(List((props,akka.actor.Props), (name,java.lang.String))),akka.actor.ActorRef,false),true,80,None), CompletionInfo(actorO>
212 23:27:29.731 DEBUG None o.e.i.ApachePollingFileWatcher - file:///code/my/playing-with-actors2/src/main/scala/TalkToActor.scala was changed
```

.ensime
```

  2  :root-dir "/code/my/playing-with-actors2"
  3  :cache-dir "/code/my/playing-with-actors2/.ensime_cache"
  4  :scala-compiler-jars ("/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.8.jar" "/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar" "/root/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar" "/root/.ivy2/cache/org.scala->
  5  :name "playing-with-actors2"
  6  :java-home "/usr/lib/jvm/java-8-openjdk-amd64"
  7  :java-flags ("-Xss2m" "-Xms1024m" "-Xmx1024m" "-XX:ReservedCodeCacheSize=128m" "-XX:MaxMetaspaceSize=256m")
  8  :reference-source-roots nil
  9  :scala-version "2.11.8"
 10  :compiler-args ("-feature" "-deprecation" "-Xlint" "-Yinline-warnings" "-Yno-adapted-args" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import" "-Ymacro-expand:discard")
 11  :formatting-prefs nil
 12  :disable-source-monitoring nil
 13  :disable-class-monitoring nil
 14  :subprojects ((
 15    :name "playing-with-actors2"
 16    :source-roots ("/code/my/playing-with-actors2/src/main/scala")
 17    :targets ("/code/my/playing-with-actors2/target/scala-2.11/classes")
 18    :test-targets ("/code/my/playing-with-actors2/target/scala-2.11/test-classes")
 19    :depends-on-modules nil
 20    :compile-deps ("/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.2.jar" "/root/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar" "/root/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar" "/root/.ivy2/c>
 21    :runtime-deps nil
 22    :test-deps nil
 23    :doc-jars ("/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/docs/akka-actor_2.11-2.4.2-javadoc.jar" "/root/.ivy2/cache/com.typesafe/config/docs/config-1.3.0-javadoc.jar" "/code/my/playing-with-actors2/target/scala-2.11/playing-with-actors_2.11-1.0-javadoc.jar" "/root/.ivy2/cache/org.>
 24    :reference-source-roots ("/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/srcs/akka-actor_2.11-2.4.2-sources.jar" "/root/.ivy2/cache/com.typesafe/config/srcs/config-1.3.0-sources.jar" "/root/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/srcs/scala-java8-compat_2.11-0.7.0>
 25 )
```

The repo is here:
https://github.com/casertap/playing-with-actors

here are the steps to build the exact same env as me using docker:
```
cd my/playing-with-actors/
docker-machine create --driver virtualbox scala-vim
eval "$(docker-machine env scala-vim)"
docker build -t test/scala-vim-image:latest .
docker run --name scala-vim-container -it --entrypoint=/bin/bash -v /Users/pierrecaserta/workspace/scala/my/playing-with-actors:/code/ test/scala-vim-image
```
INSIDE THE CONTAINER (/code)
```
rm .ensime
rm -rf .ensime_cache/
sbt compile
sbt gen-ensime
vim
```

**Comment by casertap** [comment]
Sorry I have updated the last post many many times :-) 
I hope you will have sufficient info to solve this.
Thanks

**Comment by ChrisCoffey** [comment]
I took a quick look at this and was able to replicate in your docker container, but not on a local copy of your code or on the ensime-server codebase. I run NeoVim locally though, so this may be the difference. I'll dig into this more tomorrow.

**Comment by casertap** [comment]
I am running iTerm and tmux.

**Comment by casertap** [comment]
Hey Chris I do not understand. To replicate my bug you need to be inside of the container and neovim is not part the the Dockerfile so it is not installed inside the container.

After building the image:

```
cd my/playing-with-actors/
docker-machine create --driver virtualbox scala-vim
eval "$(docker-machine env scala-vim)"
docker build -t test/scala-vim-image:latest .
```
you run the container and get a shell using the -it --entrypoint=/bash/bin option
```
docker run --name scala-vim-container -it --entrypoint=/bin/bash -v /Users/pierrecaserta/workspace/scala/my/playing-with-actors:/code/ test/scala-vim-image
```
I mount my local source code to /code using -v
 
Now you are inside the container and have access only to the things that were installed by the Dockerfile.
```
cd /code
rm .ensime
rm -rf .ensime_cache
sbt compile
sbt gen-ensime
vim
:EnClasspath
```

**Comment by jvican** [comment]
Hi @casertap!
  
I think that your problem is that you miss a dependency. From the [installation guide](http://ensime.github.io):
Install Python’s websocket-client so that the plugin can communicate with ENSIME server.
```bash
 $ sudo pip install websocket-client 
```
  
I don't see that you're indeed installing this dependency in your `Dockerfile`.

**Comment by casertap** [comment]
line 48.
yes it is install, the problem comes from something else.
I will install neovim and try.

**Comment by jvican** [comment]
I'm sorry, I confused this issue with another one. I thought your problem was a messaging problem but it seems that it's only related to the completion. I will look into it soon.

**Comment by casertap** [comment]
Ok, no worries.
I am really interested in using vim (and not emacs) as my development tool for scala. The only thing I will need is to see the different signatures for a method.
Tell me if you need anything.

**Comment by casertap** [comment]
I added neovim to the container. 
This means that ones are inside of the container, you can run nvim. 
ensime-vim should be installed already but I had some trouble making ensime work with nvim.
 
As you can see in my dockerfile ( https://github.com/casertap/playing-with-actors/blob/master/Dockerfile ), I add Vundle to .janus and I 
```
RUN cat /vundle_config.txt >> /root/.config/nvim/init.vim
```
meaning that I have Vundle and ensime installed automatically in nvim in my container using
```
RUN nvim +PluginInstall +qall
```
This will allow you to play with nvim as well. 
(I should say that I prefer using a simple vim with janus config than nvim)

Take some time to review the Dockerfile. It is quite small once you remove all the comments.

**Comment by ChrisCoffey** [comment]
Hi @casertap, there was a bug in the omni-complete handler for Vim. Vim and Neovim have subtly different apis for handling omni-completion, and in fixing the Neovim one recently I broke compatibility with Vim. There is a pull ready for review now that will resolve this.

Thanks for the details replication steps on this issue, it was very helpful.
