### ISSUE TITLE
:EnRefactor only updates local file

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#195]
The diff based refactor handling in the vim client only update the local file, while renaming a symbol should change all occurrences of it in the source. 

Based on the (Scala Refactoring)[http://scala-refactoring.org/rename/] documentation, a `Rename` should trigger some sort of user interaction if the symbol is accessible beyond the current file. In the vim client, we simply update any occurrences of the symbol in that file & continue on as if everything is alright. This is incorrect and leads to compile failure for non-local renames.

I think we should either fix this or rename the command `:EnRenameLocal`

**Comment by jvican** [comment]
`EnRefactor` is expected to work once this issue is resolved: https://github.com/ensime/ensime-server/issues/1133. So we should wait until that. The `EnRefactor` behaviour is explained in the docs.
