### ISSUE TITLE
Unknown operator when using syntastic

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#200]
Hi @kstep, here you have the info of the bug I told you about. I just have to `:w` on any recent opened file and I'll get these errors in the blink of an eye. I am using neovim but this is also reproducible with vim. I am using `vim-scala` as well, which provides Scala highlighting and a lot of other useful stuff (it uses syntastic as well).
  
Screenshot:
![2016-03-18-203947_1920x1200_scrot](https://cloud.githubusercontent.com/assets/2462974/13890190/771d27ca-ed4a-11e5-97f6-2b3884556207.png)

**Comment by ChrisCoffey** [comment]
@jvican is this on a separate build of ensime-vim? I just tried repping this on the f-p project and didn't have any issues, despite using Syntastic and vim-scala as well.

Here's my `:SyntasticInfo`:

```
Syntastic version: 3.7.0-99 (Vim 704, Darwin)
Info for filetype: scala
Global mode: active
Filetype scala is active
The current file will be checked automatically
Available checkers: ensime fsc scalac
Currently enabled checkers: fsc scalac ensime
```

could you share yours as well?

**Comment by jvican** [comment]
Mine:
```
Syntastic version: 3.7.0-101 (Vim 704, Linux)
Info for filetype: scala
Global mode: active
Filetype scala is active
The current file will be checked automatically
Available checkers: ensime fsc scalac
Currently enabled checkers: fsc scalac
```
The only difference is that ensime is not listed in `Currently enabled checkers`.

**Comment by ChrisCoffey** [comment]
I actually manually added ensime to my checkers right before posting that
output, so it seems that our setups are identical, yet I don't see any
issues.

Are you running python 2.7 or 3?

**Comment by jvican** [comment]
You have to do it on the branch `feature/add-map-flatmap`. But anyway, I just found the error. The problem comes from the server, since I receive these messages (note the weird parameters and, especially, the `-1`s which are the one causing the error since syntastic expects positive numbers.)
  
Message:
```
2016-03-19 19:29:15.519715: unqueue: result received {
  "payload": {
    "typehint": "NewScalaNotesEvent",
    "isFull": false,
    "notes": [{
      "beg": -1,
      "line": 1,
      "col": 0,
      "end": -1,
      "file": "/data/rw/code/scala/f-p/core/src/main/scala/fp/SiloRef.scala",
      "msg": "Unused import",
      "severity": {
        "typehint": "NoteWarn"
      }
    }]
  }
}
```
  
I'll be submitting a PR to fix this in some hours. Also, I think I just found the reason why vim gets blocked when exiting.

**Comment by jvican** [comment]
@fommil is this a new bug in `ensime-server`?
