### ISSUE TITLE
YouCompleteMe `UnicodeDecodeError`

### ISSUE THREAD

**Issue by gigiigig** [ensime/ensime-vim#205]
I have this error using ensime and YouCompleteMe together, 
I have a small projects where it works well but in bigger projects I get this error when I press `.` and youcomplete me should create the list of suggestion, in I press enter to close the error and then keep typing the suggestions appear, so ensime is working properly. 
```
Error detected while processing function youcompleteme#Complete..<SNR>104_GetCompletions..provider#python#Call:
line   18:
UnicodeDecodeError('ascii', '\x92', 0, 1, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/Cellar/neovim/0.1.2/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 0: ordinal not in range(128)
```

This is my config: 
Mac Os 10.11.4
NeoVim 0.1.2 
Ensime 0.4.1-SNAPSHOT

The plugins are managed with VimPlug, all updated.

Thanks,
Luigi

**Comment by jvican** [comment]
This has already been reported before and it's related to an error with the Python version. It'm not sure if it's an `ensime-vim` error (I think that someone fixed it by playing around with `YouCompleteMe`).
  
However, I think I know what's happening. I'll be submitting a PR to address this problem early tonight.

**Comment by ChrisCoffey** [comment]
@gigiigig see #182 that @jvican referenced

**Comment by jvican** [comment]
Thanks for the reference @ChrisCoffey! I couldn't find it.

**Comment by gigiigig** [comment]
@jvican @ChrisCoffey I applied that fix to YCM and it works now, thanks! Feel free to close the issue if this can't be fixed form ensime-vim.

**Comment by gigiigig** [comment]
Nope, had the same error after a while.

**Comment by jvican** [comment]
Ah! I know what's happening: ensime-server returns non-ascii symbols like arrows and stuff, so when YCM tries to decode the strings it fails. This is a YCM bug and you should go there to ask for a solution @gigiigig.

**Comment by gigiigig** [comment]
@jvican Ok I'll ask them then, Thanks!
