### ISSUE TITLE
Don't write file when invoking completion

### ISSUE THREAD

**Issue by ches** [ensime/ensime-vim#220]
Currently `complete_func` invokes `self.vim_command("write_file")` when starting completion—is this necessary?

My assumption is that it was done either to try to get the most up-to-date accurate state of source possible, and/or to be extra cautious in case of a crash being caused. But it's super annoying if, say, you're using sbt triggered execution: compiles are certainly going to fail when I'm in the middle of writing a statement 😄   Considering how frequently this will happen (especially with YouCompleteMe automatically invoking `omnifunc` on-the-fly e.g. when I type `.`), it's really noisy and probably quite a drain on laptop batteries…

I could submit a PR removing the `"write_file"` but wanted to make sure I understood the context.

**Comment by jvican** [comment]
Actually yes, go ahead, it's no longer necessary ;)
