### ISSUE TITLE
MacVim support

### ISSUE THREAD

**Issue by kiambogo** [ensime/ensime-vim#222]
I've followed the installation docs, and Ensime is working when using vim through terminal. 
However, when opening a Scala file with MacVim the following appears

    websocket-client missing: do a `pip install websocket-client` and restart vim

The websocket-client is installed, as proved by the fact that Ensime is working in vim through terminal. Any idea why MacVim would not be finding the websocket-client?

**Comment by ches** [comment]
How did you install MacVim, and is the terminal `vim` on your path the OS X system `/usr/bin/vim` or something else? Chances are that they're built against different Python installations and the Vim you're launching in terminal is using the one where you've got `websocket-client` installed. This can be a bit of a hassle to keep straight…

Personally I install with Homebrew using:

    $ brew install python
    $ brew install macvim --with-luajit --with-lua --with-override-system-vim

`/usr/local/bin/vim` should then be MacVim (runnable in terminal, or GUI with `mvim` or an icon with `brew linkapps macvim`). Double-check that `which pip` now reflects the Homebrew prefixed `pip` and not in `/usr/bin`. Then `pip install websocket-client`, and hopefully that should do it…

**Comment by kiambogo** [comment]
Great - thanks for the information. I think you were correct in stating that they're built against different Python installations. I re-installed MacVim, and symlinked pip in `/usr/local/bin` to point to the Homebrew-installed pip and things are working now. :)

**Comment by jvican** [comment]
Thanks for taking over this @ches.
