### ISSUE TITLE
Make implementation details of Package Inspector private, instead of using commands

### ISSUE THREAD

**Issue by ches** [ensime/ensime-vim#231]
The Package Inspector feature has used two commands which are essentially internal implementation details, `:EnPackageDecl` and `:EnSymbolByName` (see #217). These lead to confusion like #239, and the below struck-out stuff of my own.

I think we could support the feature with greater encapsulation. My initial thought was using script-scoped functions (`s:foo`), exposed/called as a `<Plug>` mapping in the case of `:EnPackageDecl`.

The functionality of `:EnSymbolByName` might make sense to leave as a "public" function (the current `ensime#com_en_symbol_by_name`) and maybe even leave the command too (but document it), but I'm not sure how it practically differs from `:EnDeclarationSplit` in use case, I haven't closely compared the code for the two yet. Maybe a refactor could combine them?

~~I just realized that this command exists but isn't documented. It doesn't seem to work.~~

### ~~Steps to reproduce~~

~~1. Run `:EnSymbolByName something`~~
~~2. Wait for a response~~

### ~~Expected behaviour~~

~~I think the intended behavior is to echo where the symbol is defined, like `:EnSymbol` does but taking an arbitrary argument instead of using `<cword>`.~~

### ~~Actual behaviour~~

~~Nothing happens.~~

**Comment by ches** [comment]
Forgot to note in the issue body: I'm guessing this command might need to be wired up like #227 did.

**Comment by ChrisCoffey** [comment]
It's actually not intended to work like `:EnSymbol` but rather like ':EnDeclarationSplit v', so this is more of an issue with the naming than anything else. 

I added this to support the Package Inspector's jump-to-definition

**Comment by ches** [comment]
Oh right, I completely forgot (and wasn't looking at the source) that it was an implementation detail of the Package Inspector. Could we just use a function for that (possibly private, `s:foo`), instead of exposing a command? I know you had reservations about that before. This was the case that made me think about instead exposing a `<Plug>` mapping to such a function, so users could change the mapping without a command being needed.

When I can make time I'll try to work up a pull request to show what I mean.

**Comment by ChrisCoffey** [comment]
That'd be great. I'll take a stab at this as well later tonight.
