### ISSUE TITLE
No handler for BufEnter or other autocommand events

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#237]
There's no handler for the event `BufEnter`, which usually gets fired when switching between windows of different plugins. An exception is thrown. I'll add one in the next days.

**Comment by jvican** [comment]
This error typically happens when neovim remembers that there should be a handler for `bufenter`, `bufwrite`, etc. The solution is to execute: `:UpdateRemotePlugins`.

**Comment by ChrisCoffey** [comment]
Is this actually an issue, or was it simply an outdated definition in neovim that `:UpdateRemotePlugins` resolved?

**Comment by jvican** [comment]
As I pointed out before in my last comment, it was solved by doing `:UpdateRemotePlugins`.
  
I'm going to leave this issue opened for a while in case it happens to other people, as it's a pretty recurrent problem with neovim.

**Comment by ches** [comment]
I've added a "faq" label for this and will link to an issue search for that label from the web docs soon, as some of the other ENSIME projects do in their troubleshooting sections.
