### ISSUE TITLE
Create a deoplete source

### ISSUE THREAD

**Issue by NickHu** [ensime/ensime-vim#238]
It would be great if this ensime had a deoplete source, documented [here](https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L541), for asynchronous code completion.

**Comment by jvican** [comment]
Yes, it would be great. Feel free to contribute to the project and make a PR :smile:

**Comment by yyadavalli** [comment]
deoplete has an `omni` source, which takes a vim regex pattern based on filetype. I was able to get autosuggestions based on that.

```
let g:deoplete#sources={} 
let g:deoplete#sources._=['buffer', 'member', 'tag', 'file', 'omni', 'ultisnips'] 
let g:deoplete#omni_patterns={} 
let g:deoplete#omni_patterns.scala='[^. *\t]\.\w*'
```

If we have good pattern this is should be good.

The only issue may be that `omni` source is not asynchronous in deoplete.

**Comment by jvican** [comment]
Thanks @yyadavalli, very valuable information. We will probably add this to the docs soon. :grinning:

**Comment by yyadavalli** [comment]
Welcome @jvican, any suggestions on a better pattern would be really helpful.

**Comment by NickHu** [comment]
The first two lines of your config aren't necessary.

**Comment by ktonga** [comment]
The main disadvantage of using `g:deoplete#omni_patterns` is that `omnifunc` is called from Vim in a synchronous way, so it blocks you typing until the completion is ready.
After merging #259, `g:deoplete#omni#input_patterns` can be used instead, so the completion will be processed asynchronously while you keep typing. It's the setting recommended in __deoplete__'s documentation.
