### ISSUE TITLE
Hangs on classpath generation

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime-vim#249]
Running `:EnClasspath` hangs with the message `Waiting for generation of classpath...`
on `NVIM 0.1.4 after #242

Exploring `top` shows that sbt was not started, so I believe there is a problem with the terminal command constructed.

The issue was fixed by reverting 
`self.vim.command("terminal sh \"({} && {})\"".format(cd_cmd, sbt_cmd))`
to
`self.vim.command("terminal ({} && {})".format(cd_cmd, sbt_cmd))` -- old version
or 
`self.vim.command("terminal sh \"$({} && {})\"".format(cd_cmd, sbt_cmd))`

I think the underlying problem is `(cmd)` works as command substitution for fish so `cmd` is passed on to sh, but for other shells command substitution is in the form `$()`

The only workaround I can think of is detecting the shell in vim and constructing the command accordingly

**Comment by jvican** [comment]
Introduced by https://github.com/ensime/ensime-vim/pull/242. Up for a PR @yyadavalli ?

**Comment by yyadavalli** [comment]
@jvican Sure, do you have any other ideas for a workaround or should I just put in a check for `fish`
