### ISSUE TITLE
Support Local Assembly Jar

### ISSUE THREAD

**Issue by ChrisCoffey** [ensime/ensime-vim#260]
Right now Emacs supports an alternative startup mode where the presence of a local version of the Ensime server jar circumvents the classpath file. This would be extremely useful for local testing.

Right now my workaround is to bump the server version, publish locally, bump the version the plugin looks for, then remember to roll back all the version changes & remove the local version from my `.ivy` cache. This is a pretty messy procedure that I forget to unwind sometimes.

**Comment by yyadavalli** [comment]
@ChrisCoffey what do you think would be a good location to check for the presence of a jar. I can make this change and send a PR

**Comment by ChrisCoffey** [comment]
I'd be happy supporting a jar in `~/.config/ensime-vim/`. The presence of a jar there should be placed at the head of the classpath.

**Comment by yyadavalli** [comment]
@ChrisCoffey wouldn't it replace the classpath from file
