### ISSUE TITLE
Completion: Several problems regarding type formatting

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-vim#273]
In the completion popup, specially for __functions__, the type hint may be ok for simple signatures, but it easily gets messy for complex ones. Here you have an example for `Seq.fill`:

What __Intellij Idea__ reports:
<img width="709" alt="screen shot 2016-06-03 at 9 59 43 pm" src="https://cloud.githubusercontent.com/assets/1324947/15777970/907c371a-29d6-11e6-8507-a0c4ad3606ca.png">

What __ensime-vim__ reports:
<img width="1384" alt="screen shot 2016-06-03 at 9 18 01 pm" src="https://cloud.githubusercontent.com/assets/1324947/15777613/1e5b03b6-29d4-11e6-9883-7b3238f4e428.png">

I can see a few problems so far:

- [x] Only the first entry is shown for overloaded functions (but all are present in server's response)
- [ ] Type parameters are not included at all
- [x] Only the first argument list is used
- [x] Fully qualified names are used which gets pretty unreadable

Now that ensime/ensime-server#1468 has been merged these problems seems quite simple to solve. I will start working on it and hopefully I'll be raising a PR in a few days.

**Comment by ChrisCoffey** [comment]
Sounds great. Please ask if you get stuck.

**Comment by jvican** [comment]
Regarding the "fully qualified names" issue, you can work around it by using the ensime command `EnToggleFullType`.

**Comment by ktonga** [comment]
@jvican I checked the code and it formats the signature directly using the "sections" field which only has the full names and is hard to manipulate due to its lack of structure.

On a side note, I don't think it's necessary to make it configurable. 93% of the times, full names in the signatures is useless and confusing. I saw this number once in a Harvard research :P

**Comment by ktonga** [comment]
Well, today I was able to make some progress, and this is the result so far:

Before
![snapshot12](https://cloud.githubusercontent.com/assets/1324947/15830185/5499b84a-2c5a-11e6-8d68-ee248e4895c8.png)

After
![snapshot13](https://cloud.githubusercontent.com/assets/1324947/15830200/656c70b8-2c5a-11e6-8c8a-b6fd0da70ed1.png)

It's almost finished, I'm only missing a way to add the type params to the generic methods, but I cannot figure it out with the actual structure of `typeInfo`. I've already asked about it in __ensime-server__ gitter channel.

I have a few more improvements in mind but I'll propose them in separate issues/PRs.

Cheers.

**Comment by ktonga** [comment]
Adding type params list to methods signature is not possible with the available information in the response.
It will need some work on the server first. So let's track it with #276

**Comment by aemoncannon** [comment]
looking good so far...

**Comment by fommil** [comment]
btw you might want to consider using `:name` instead of `:full-name` to keep the completion view manageable! :smile:
