### ISSUE TITLE
EnDocBrowse prepends localhost

### ISSUE THREAD

**Issue by Jacoby6000** [ensime/ensime-vim#274]
To repro:

```scala
def foo(date: java.sql.Date) = date.getSeconds()
```

Call `EnDocBrowse` with the cursor hovering over `getSeconds`

Resulting URL is
```
http://127.0.0.1:59102/http://docs.oracle.com/javase/8/docs/api/java/sql/Date.html#getSeconds--
```
Expected
```
http://docs.oracle.com/javase/8/docs/api/java/sql/Date.html#getSeconds--
```

**Comment by jvican** [comment]
Are you sure this is not an issue of the server? It really looks like it is.

**Comment by ChrisCoffey** [comment]
@Jacoby6000 you're correct that we prepend `http://127.0.0.1/<ensimePort>/` onto the doc uri response. Unfortunately all we get back from the server is a string, so whatever we do will be a bit hacky. 

That being said, a simple check whether the response string starts with `http` should go a long way to resolving this.

**Comment by jvican** [comment]
In that case, a simple PR should address this easily. Up for it @Jacoby6000 ?

**Comment by Jacoby6000** [comment]
PR made :)
