### ISSUE TITLE
Omnicompletion patterns for deoplete.

### ISSUE THREAD

**Issue by Jacoby6000** [ensime/ensime-vim#282]
In #238 I mentioned making standard deoplete omnicompletion patterns. I've come up with these patterns, and it seems to be working very well for me. 

``` vim
let g:deoplete#omni#input_patterns.scala = [
  \ '[^. *\t]\.\w*',       "omnicompletion for "foo.*"
  \ '[:\[,] ?\w*',         "omnicompletion for ":*" ",*" "(*" and "[*"
  \ '^import .*'           "omnicompletion for imports
  \] 
```

I think the only case I'm missing right now, is when typing at the beginning of a line, but I'm not sure that's a big deal anyway.... well maybe it is. I dunno. 

Once we hammer these out a little better, I'll make a PR for adding them in to ensime-vim.

**Comment by jvican** [comment]
This is great. If the beginning of a line is not working it wouldn't be such a big issue, it's quite uncommon we want autocompletion if we haven't typed anything yet. Could you do a PR?

**Comment by Jacoby6000** [comment]
Looking back at this, we should change this issue in to making ensime-vim in to a completion source, rather than using omnifunc (which is synchronous).  I actually stopped using ensime-vim because omnifunc was so slow, and other tools can get me everything else.  I'd definitely come back if there were async completion sources.

**Comment by vito-c** [comment]
@Jacoby6000 what are you using as a  completion source for scala code with deoplete?

**Comment by Jacoby6000** [comment]
Currently nothing.  I just use [stags](https://github.com/pjrt/stags).  It's good enough for navigating local source.  For 3rd party dependencies, my workflow could be better for sure.
