### ISSUE TITLE
Overhaul logging and only do tracing when a debug flag is active

### ISSUE THREAD

**Issue by ches** [ensime/ensime-vim#297]
I think it's time to create a issue to track this as a TODO. The plugin's logging approach is pretty simplistic and heavy-handed—it's a homegrown `log` function that appends to a non-configurable file, re-opening a file handle on every call, and our logging is mostly trace-level detail that's quite verbose.

This is great when you're debugging or working on a new feature and want to see the server communication, so it probably served well in the plugin's early life, but I believe it has a real performance cost. Consider times when there is a lot of traffic exchange especially, like debugging: the server sends events for every thread start and thread death. If you're running code with `Future`s, for instance, ensime-vim spends a fair amount of time receiving and logging all these messages that we don't currently even handle.

We should consider a leveled logging approach to improve this, at least two levels, probably the equivalent of `INFO` and `TRACE`/`DEBUG`. Also, it would be nice to clean up and automate messy manual trace logging with decorators.

This might be a good newbie task since it doesn't require much familiarity with ENSIME specifics but you will get to know the code base in the process.

This perhaps could be broken into steps:

1. Move to a persistent `logging.Logger` instance, avoiding all the excess file handle opening. The log sink could be made configurable so e.g. test harnesses can send it to standard out/err (more palatable after trace output is not on by default…), while file remains the default since that's what is sensible when running in Vim.
2. Change trace logging to use an appropriate log level. Ideally try to avoid unnecessary work like pretty-formatting data structures when they're not being logged at higher levels (I don't think we actually explicitly do this now, but just an example). The level should be the `INFO` equivalent by default, with a Vim config variable to change it which we can ask users to set when troubleshooting.
3. Get rid of noisy trace logging statements that pervade the code base using decorators. [Autologging] looks nice, there are other similar solutions if we're willing to accept a pip dependency for this.

If we're willing to use a third-party dep it might be easy to just skip to step 3 and get most of this for free.

[Autologging]: http://pythonhosted.org/Autologging/

**Comment by ChrisCoffey** [comment]
I'd be happy with this landing in two or even a single pull, provided we go the decorator route. 

Autologging does look quite nice. That being said, I think the attractiveness of the package lies in the decorators, and I'm not sure they're worth the cost of requiring users to install a third package (although I could go either way on this since I really don't like reinventing things).

Thoughts on package vs. roll our own?

**Comment by ches** [comment]
I think the most important parts of this were covered by #323, and since I'd agree with not adding a dependency to get the magic decorators that won't even be a user-visible improvement, I think I'll close this for now.

The logging isn't very configurable at this point, just an environment variable to toggle between `INFO` or `DEBUG` log level, but if a desire for more comes up in practice we can handle it as a new issue.
