### ISSUE TITLE
Rename :EnClasspath

### ISSUE THREAD

**Issue by ches** [ensime/ensime-vim#303]
Just a small thing, but it keeps crossing my mind so here goes:

`:EnClasspath` is the first thing an ensime-vim user ever runs, and the name is kind of puzzling. It's basically an implementation detail that the server installation needs to be bootstrapped with the classpath file generated for its launch. What if we changed this to a more self-describing name from the user's perspective, like `:EnInstallServer` or something like that? Or maybe even just `:EnInstall`.

**Comment by ches** [comment]
We could also include the project Scala version in the feedback message that's displayed, hopefully making it apparent that it's normal to need to run it again for a different ABI:

> [ensime] Please run :EnInstall to install the ENSIME server for Scala 2.xx

**Comment by jvican** [comment]
That's a great idea, would you mind making a PR?
