### ISSUE TITLE
E319: Sorry, the command isn't available in this version: python <<PY

### ISSUE THREAD

**Issue by stevendobay** [ensime/ensime-vim#306]
### Steps to reproduce

1. Installed 

Ubuntu 16.04, 

Scala 2.11.8, SBT 0.13.11, 

OpenJDK8, 

Python 2.7 + pip 8.1.1 + websocket-client + sexpdata, 

latest vim-scala & ensime-vim & ensime-server & ensime-sbt from Vundle

~$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)

2. Created a hello-world sbt project to test vim 
3. Opened Main.scala with Vim
4. Typed ":EnInstall" - no luck

### Expected behaviour

Working ensime-vim

### Actual behaviour

Error when opening .scala files:

Error while processing function ensime#au_vim_enter[1]..<SNR>66_call_plugin

Error while processing function ensime#au_cursor_moved[1]..<SNR>66_call_plugin

E319: Sorry, the command isn't available in this version:     python <<PY

After ":EnInstall" - Error while processing function ensime#com_en_install[1]..<SNR>66_call_plugin

**Comment by tjakway** [comment]
Also experiencing the same issue.

**Comment by ches** [comment]
Hi,

> E319: Sorry, the command isn't available in this version: python <<PY

You're running a version of Vim that isn't built with support for Python plugins (or possibly only with Python 3 support, ensime-vim currently requires Python 2 support.

Please review [the installation page][1] again: it asks that you confirm `vim --version | grep +python` (looking for `+python` in the output, not `+python3`).

I'm not sure about Ubuntu 16.04 specifically, but distributions normally have a Vim package that is built with Python support (a `vim-tiny` package likely will not). Let us know how you're installing Vim so we can try to guide you further if you can't get it working.

I'll create an issue for us to report a better error message when the Vim is missing Python support.

[1]: https://ensime.github.io/editors/vim/install/

**Comment by ches** [comment]
Ah, realized that on the installation page I linked above we actually specifically address Ubuntu 16.04 already 😝

**Comment by tjakway** [comment]
I'm running Mac OS X and built vim from source.  It most definitely has python2.  And I don't get this line 

`E319: Sorry, the command isn't available in this version: python <<PY`

Just

```
Error while processing function ensime#au_vim_enter[1]..66_call_plugin

Error while processing function ensime#au_cursor_moved[1]..66_call_plugin
```

Will update with more details tomorrow when I'm at that computer again.

**Comment by ches** [comment]
@tjakway Your issue is definitely different then, please open a new issue when you're back in position to gather info. Be sure to check [the troubleshooting guide][1] first.

[1]: https://ensime.github.io/editors/vim/troubleshooting/

**Comment by stevendobay** [comment]
Hi @ches ! Thanks, it kinda worked, however, the user should purge all vim packages first(sudo apt-get remove vim*) to install vim with python2 support properly(sudo apt-get install vim-nox-py2). Will ensime-vim support python3 in the future?

**Comment by ches** [comment]
Good to hear, sorry it's a bit of a hassle to switch packages.

> Will ensime-vim support python3 in the future?

I'm sure we will eventually, the code is probably not very far from working in Python 3 already if we just added detection for which the user's Vim supports. I just don't think any of us have really worked on testing that and trying to make it work yet.

**Comment by byYufeng** [comment]
apt install vim-nox-py2

ref:
https://askubuntu.com/questions/284957/vi-getting-multiple-sorry-the-command-is-not-available-in-this-version-af

**Comment by lilred** [comment]
FYI, Ubuntu does not offer `vim-nox-py2` anymore.

**Comment by PabTorre** [comment]
I was seeing a similar issue on ubuntu 16. 

just changed the line to 
`py3 << EOF`

and it loads without errors now. 🔢
