### ISSUE TITLE
Ensime server not initialized

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-vim#33]
__Description__: When opening a scala file, all the commands of the plugin are visible and executable. However, every command gives the following response: "still initialized". Then, the plugin is not working.

__Using__:
* ``nvim`` 0.0.0-alpha+201509092022
* ``scala`` 2.11.7
* ``sbt`` 0.13.9 with sbt-ensime plugin installed in ``~/.sbt/0.13.9/plugins/plugins.sbt``
* ``python2`` and ``python3`` with ``websocket-client`` and ``neovim`` dependencies installed
* ``vim-plug`` latest version

__Previous diagnosis__:
* The problem is due to that the run method of EnsimeLauncher is never executed, hence the attribute _self.ws_ is ``None`` and "still initialized" appears in nvim
* Incorrect execution of ``ensime.py``. When looking at htop, two processes besides the main nvim are running:
  - python2 -c import neovim; neovim.start_host() /home/jvican/.vim/plugged/ensime-vim/rplugin/python/ensime.py
  - python2 -c import neovim; neovim.start_host() /usr/share/nvim/runtime/autoload/provider/script_host.py
    
  
However, when executing them independently in a console, they don't work. neovim.start_host() complains about not getting an argument and there is no trick to solve it. You cannot even pass the paths are arguments of that function.
* jps says ensime server is not running
  
__Important remark__: I am sharing vim configuration files with nvim. I don't think this is a problem but I am saying it just in case.

**Comment by jvican** [comment]
Also, when executing nvim with the verbose option ``nvim -V10 file.scala``:
  
``autocommand call remote#define#AutocmdBootstrap("python", "...")`` where the dots represent paths to ensime.py and more arguments responding to the ``CursorHold`` event.
  
It looks like it could be a problem of nvim calling a bad version of python? Here it is python3, not python2. When ``ensime.py`` is executed with Python3, import errors happen (thread => _thread in PY3, Queue not existing, etc)

**Comment by jvican** [comment]
With the last pull request, I have been able to make it work.
For people with the same issue: __Don't update or remove using only _:PlugUpdate_ or :_PlugClean_ __
In my case, I had to remove the folder ensime-vim in .nvim/plugged/ensime-vim manually. Then, I installed ensime-vim again and the pluggin worked. I didn't get this result with PlugClean.
__NOTE__: I am using vim-plug.

**Comment by yazgoo** [comment]
Thanks jvican.
