### ISSUE TITLE
Remove LGTM integration in favor of Required Reviews

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-vim#338]
GitHub has recently added support for PR reviews:
https://help.github.com/articles/about-pull-request-reviews/
https://help.github.com/articles/about-required-reviews-for-pull-requests/

I think this new native feature solves what we are enforcing with `lgtm` but in a much better way. Shall we enable it and remove `lgtm` integration?

**Comment by ches** [comment]
I haven't actually tried out the required review workflow yet on any project, but in principle the switch makes sense to me.

**Comment by ktonga** [comment]
Hey @fommil could you do the switch please?

**Comment by fommil** [comment]
done!

**Comment by ktonga** [comment]
Thanks!
