### ISSUE TITLE
Error highlighting doesn't work anymore

### ISSUE THREAD

**Issue by gigiigig** [ensime/ensime-vim#339]
Error highlighting stopped worked recently in Neovim, I can't really say when but around one month ago I think, vim still sees the errors coming from the server, and they are reported in Vim in the message area on the bottom, but they are not highlighted.

This is my configuration: 

Neovim: NVIM 0.1.3-dev Build type: Dev  

I tried with sbt-ensime plugin version: 1.0.0 and 1.9.0 and 1.9.1-SNAPSHOT
all have the same problem.

Thanks, 
Luigi

**Comment by ches** [comment]
Thanks for the report—I assume that you're *not* using Syntastic, correct? I did some refactoring recently that must have broken the "native" error highlighting support in ensime-vim, I admittedly didn't test that well. I'll try to reproduce.

**Comment by gigiigig** [comment]
Correct, I'm not using Syntastic indeed, I tried to install it and works with Syntastic, thanks!
