### ISSUE TITLE
Unreliable `EnTypeCheck`

### ISSUE THREAD

**Issue by netzwerg** [ensime/ensime-vim#342]
### Steps to reproduce

1. `git clone https://github.com/fhnw-saav/saav`
2. `sbt ensimeConfig`
3. `vim src/main/scala/ch/fhnw/ima/saav/MainApp.scala`
4. `:EnTypeCheck`
5. `:EnTypeCheck`

### Expected behaviour

Step 4 should kick off type checking, resulting in error highlights.

### Actual behaviour

Step 4 completes immediately and does not highlight errors:
```
[ensime] Typechecking...
Press ENTER or type command to continue
```

After another invocation (step 5), everything works as expected (an error on line 62).

[ensime-vim-log.txt](https://github.com/ensime/ensime-vim/files/503014/ensime-vim-log.txt)

**Comment by ktonga** [comment]
It seems you are trying to type-check before the server is ready. Please wait until you see the message from the server when it's ready in the status bar, then trigger the check. That should give you the expected behaviour.

**Comment by netzwerg** [comment]
I see `[ensime] Server has been started...` pretty much immediately. Still it takes two or more `EnTypeCheck` invocations to get an actual type check.

Attached another log, hope it helps...

[ensime-vim-log.txt](https://github.com/ensime/ensime-vim/files/503402/ensime-vim-log.txt)

**Comment by netzwerg** [comment]
Just made a weird observation:

Inside VIM, when I type ":EnType" and then press the tab key until "EnTypeCheck" is focused, and then press return, the type checking always completes immediately and no errors are highlighted.

However, when I type in the full ":EnTypeCheck" command character after character, it always works.

Maybe "correlation is not causation", but it was 100% reproducible when I tried 5x in a row 😕

**Comment by ches** [comment]
> I see `[ensime] Server has been started...` pretty much immediately. Still it takes two or more `EnTypeCheck` invocations to get an actual type check.

Sorry for the delay in responding, but this message doesn't mean the server is ready, there are two subsequent messages, "Indexer is ready" and "Analyzer is ready"—effectively you'll want to wait for both of these before you can expect the plugin to be fully functional and stable.

I'm sure we could stand to improve the messaging/behavior when user acts before the server is ready, but for now this is "working as intended" if you find that your issue isn't reproducible after waiting.

If the problem still persists despite this, feel free to re-open. Or if it bothers you enough to want to take a shot at making the behavior better, opening a new enhancement issue for that would be great.
