### ISSUE TITLE
Remove `EnFormatSource` command

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-vim#344]
Support for formatting source will be removed from server soonish (ensime/ensime-server#1606), so the removal of the command will be mandatory when talking to a server 2.0.
Since defining different commands per server version sounds so painful I see two possible options:
- Totally remove the command
- Overwrite the command handler for 2.0 as NOOP with message `Not supported in 2.0`

**Comment by yyadavalli** [comment]
I can send in a PR once we have more comments. My personal suggestion would be to remove the command

**Comment by ktonga** [comment]
That would be nice, thank you!

It's my personal preference too, TBH I never felt like a command to format the code would belong to a plugin like ensime-vim, while there are so many tools out there to achieve that in a better way.
