### ISSUE TITLE
name 'ensime_plugin' is not defined on Windows (Troubleshooting hints did not help)

### ISSUE THREAD

**Issue by paultol** [ensime/ensime-vim#346]
I installed Ensime plugin to sbt and ensime-vim plugin (using Vim-Plug) on Windows 8.1, vim 8.0.69. 

I have a simple sbt project and ensimeConfig seems to have worked fine.

> ensimeConfig
[info] ENSIME update.
[warn] SBT is using ivy to resolve dependencies which is known to be slow. Coursier is recommended: http://get-coursier.io
[info] Resolving org.scala-lang#scalap;2.11.4 ...
[info] ENSIME processing hello (Hello SBT)
[warn] Some source directories do not exist and will be ignored by ENSIME.
[warn] For example: C:\Users\Pavel\prj\sbt\hello\src\test\scala

In gvim, I receive these error messages every time I try to load .scala file or run any ensime ex command (the commands seem to be available, typing :En and pressing <TAB> lets me scroll through the commands):

Error detected while processing function ensime#com_en_declaration[1]..<SNR>39_call_plugin
line 15:
E605: Exception not caught: <type 'exceptions.NameError'>:name 'ensime_plugin' is not defined

I followed Troubleshooting hints and found that Python versions used by vim and pip modules sexpdata, websocket-client match (they both are 2.7):

results of
:py import sys; print(sys.path):
['C:\\must>not&exist', 'C:\\WINDOWS\\SYSTEM32\\python27.zip', 'C:\\pkg\\python27\\Lib', 'C:\\pkg\\python27\\DLLs', 'C:\\pkg\\python27\\Lib\\lib-tk', 'C:\\Users\\Pavel\\prj\\sbt\\hello', 'C:\\pkg\\vim\\vim80', 'C:\\pkg\\python27', 'C:\\pkg\\python27\\lib\\site-packages', '_vim_path_']

C:\Users\Pavel\prj\sbt\hello>pip show sexpdata | findstr Location
Location: c:\pkg\python27\lib\site-packages
C:\Users\Pavel\prj\sbt\hello>pip show websocket-client | findstr Location
Location: c:\pkg\python27\lib\site-packages

Please help

**Comment by paultol** [comment]
I think I found the reason: it's that ensime_init_path() in ensime.vim.py checks file path end in a system-dependent way. I patched it locally and loading scala files works for me (although further down the road server loading seems to have a similar issue but it is a completely different issue). Should I just submit a pull request or there is another procedure for submitting fixes (could not find the exact procedure on the web site)? Just in case, attaching the diffs here.
[diffs.txt](https://github.com/ensime/ensime-vim/files/577284/diffs.txt)

**Comment by ches** [comment]
Hi, looks like you're right, I've never heeded the naive string comparison going on there before, I guess we don't have many Windows users 😇 

The patch looks fine but I suspect we can probably simplify it a bit, if you can open a pull request that'd be great. Thank you for reporting and examining the issue.

**Comment by ches** [comment]
I was halfheartedly messing with this initialization approach awhile ago (looking to get rid of the duplication of the `ensime_init_path` definitions, among other aspects)—I'll have to check back to my WIP but the scope of it may go wider and not be ready. In the meantime a quick fix for system-agnostic paths is definitely warranted here.
