### ISSUE TITLE
Use Vim's timer instead of CursorHold event

### ISSUE THREAD

**Issue by Kazy** [ensime/ensime-vim#373]
Vim and Neovim now have a timer functionality to trigger and repeat a function. The related patch: https://github.com/vim/vim/commit/975b5271eed4fa0500c24a8f37be0b1797cb9db7.

While trying to fix an issue related to `CursorHold` with the `EnType` command whose result was immediatly erased from the command bar, I saw the timer patch. I decided to use it in Ensime-Vim instead of using `CursorHold`. The result is available here: https://github.com/Kazy/ensime-vim/commit/04aea153029d3411fa99f2dda1e6aeeb6f3a8bbe. 

It's a quick implementation and it has not been tested intensively. Considering the timer patch is fairly recent, I prefered to run than through an issue first to discuss its inclusion. Let me know what you think.

**Comment by jvican** [comment]
This is awesome @Kazy, thank you for taking a stab at this. Would you mind opening a PR to study the inclusion of this patch into master? I would guess that we should require all our users to bump up their vim versions to 7.4.1578.
  
Do you know if this works with `neovim`? I'm not sure if the function added in `vim` has the same interface as timers in `neovim`.

**Comment by Kazy** [comment]
Yes it's already in Neovim. Since ensime-vim already has a solution working, we could enable the timer functionality conditionally. You can test for the `+timers` feature.
