### ISSUE TITLE
errors for cursormove and cursorhold with ensime and neovim.

### ISSUE THREAD

**Issue by tmccombs** [ensime/ensime-vim#382]
### Steps to reproduce

1. Install ensime plugin using plug in neovim () on ubuntu 14.04
2. run ensimeConfig in sbt project
2. Open a scala file in above project

### Expected behaviour
Not get errors, ensime comands work

### Actual behaviour

I get the following error on almost every key press and it every couple of seconds even if I don't do anything:

```
Error detected while processing CursorHold Auto commands for "*.scala":
error caught in request handler '/home/thayne/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py:autocmd:CursorHold:*.scala ('chart-web/app/com/lucidchart/Utils.scala',)':
Traceback (most recent call last):
  File "/home/thayne/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 177, in au_cursor_hold
    super(NeovimEnsime, self).au_cursor_hold(*args, **kwargs)
```

If I press enter I see this:

```
Error detected while processing CursorHold Auto commands for "*.scala":
TypeError: super(type, obj): obj must be an instance or subtype of type
```

This makes the editor completely unusable with the plugin installed.

**Comment by tmccombs** [comment]
It is probably related to this: https://thingspython.wordpress.com/2010/09/27/another-super-wrinkle-raising-typeerror/

I am on python 2.7.6

**Comment by ktonga** [comment]
Hi @tmccombs,

Could you start vim with debugging enabled (`vim -V9vim.log`) and check in the file `vim.log` if you see any other clue what the problem can be?

Cheers.

**Comment by tmccombs** [comment]
It appears the problem was that I had copied the rplugin code into a different place in my runtime path. 

Deleting that fixed it. Although it is incredibly slow, and sometimes commands don't seem to do anything.
