### ISSUE TITLE
[Feature Request] Python 3 Support

### ISSUE THREAD

**Issue by byronyi** [ensime/ensime-vim#397]
Debian 9 is released a couple days ago and it is the first stable release that comes with Java 8. This is important to us that a lot of projects have deprecated use of Java 7, and we need a new development environment for these projects.

However, this also means that the `vim-python` package of Debian 9 all comes prebuilt with Python 3. And it is expected that EOL of Python 2 will come in next 3 years.

I am not sure if the migration needs modification only on `ensime-vim`, i.e. the plugin side, or it has to be done on the server side as well. If the former is true, I could start to work on it.

**Comment by ktonga** [comment]
We discussed about it briefly on #366 see this comment https://github.com/ensime/ensime-vim/issues/366#issuecomment-292710136

**Comment by ktonga** [comment]
>I am not sure if the migration needs modification only on ensime-vim, i.e. the plugin side, or it has to be done on the server side as well.

On response to your concrete question, no, no change on the server would be needed.

**Comment by ktonga** [comment]
Closed by #411 

Thank you @Ch00k !!!
