### ISSUE TITLE
Not working on neovim, but no feedback of any failure

### ISSUE THREAD

**Issue by mlopes** [ensime/ensime-vim#406]
Hi, I'm using neovim v0.2.0, sbt 0.13.16 and sbt-ensime 1.12.5. Installing ensime-vim via vim-plug, with:

`Plug 'ensime/ensime-vim'`

:UpdateRemotePlugins doesn't show any errors:

```
remote/host: python host registered plugins ['ensime.py']
remote/host: generated rplugin manifest: /home/mlopes/.local/share/nvim/rplugin.vim
````
And the :En* commands are all available in vim. Running `ensimeConfig` in sbt also doesn't show any errors, but when I run the :En* commands, nothing happens, and I get no feedback reporting any kind of failure.

Am I doing anything wrong, or did I stumble upon some bug?

**Comment by ktonga** [comment]
The steps you're describing sound good so far.

Try starting neovim with `ENSIME_VIM_DEBUG=1 nvim` that will enable a little more of debug in the log file `.ensime_cache/ensime-vim.log` take a look there if you see anything suspicious.

**Comment by mlopes** [comment]
Thanks, that helped me after some tweaking around with versions.
So apparently I had some version conflict  as the project is running on scala `2.11.7`, downgraded to ensime-vim `1.11.3`, and when I tried to use it, neovim told me to run EnInstall, which exited without errors apparently. But now I see this in `~/.ensime_cache/server.log`:

```
Error: Could not find or load main class org.ensime.server.Server
```

**Comment by ktonga** [comment]
Just try with the latest for everything, update vim plugin, now it's defaulting to server 2.0 and use latest sbt plugin. Clean all the old jars you may have in ivy and coursier caches and run ensimeConfig again. That should solve your issues.

**Comment by mlopes** [comment]
Going to try that, unfortunately for the project I'm working on now, I can't change the Scala version. But I got it working with an older version of the plugin in the 1.12.x (sorry I'm not currently on the computer, and can't remove the exact version). The server starts and gets calls from the plugin, I'm just not getting any data now, but I suspect that's probably configuration.

**Comment by mlopes** [comment]
Confirmed it works with scala 2.12.3, event though I had to specifically configure ensime to use that scala version otherwise it would conflict with the project saying that ensime was trying to use 2.10.x.
