### ISSUE TITLE
Option to change the background color on type check errors

### ISSUE THREAD

**Issue by xanderdunn** [ensime/ensime-vim#44]
Right now, executing `: EnTypeCheck` will show an orange background on any symbol that isn't resolved correctly:
<img width="999" alt="screen shot 2015-09-16 at 22 35 31" src="https://cloud.githubusercontent.com/assets/1313618/9925698/435f6a3c-5cc3-11e5-9878-df62fa9cea8d.png">

Is there an option to change this color?  

Ideally, I'd like to be able to add the option to show gutter symbols rather than change background colors.  Rather than flashing the error messages momentarily at the bottom of vim, we could have the messages be persistent so that it shows up whenever my cursor is sitting on the line, or the word, that has the highlight/gutter symbol.

**Comment by yazgoo** [comment]
I've just pushed this commit:

https://github.com/yazgoo/ensime-vim/commit/b632cda4e0974bc52805f19e830a8a5027b44244

Does it do what you'd expect ?

**Comment by yazgoo** [comment]
(For the first part i mean)

**Comment by yazgoo** [comment]
Here is the second part (hover support).

**Comment by xanderdunn** [comment]
@yazgoo Wow, you're really on top of this!  Thanks so much!!  I'll try this out tonight.

**Comment by todesking** [comment]
In `syntastic` plugin,  error highlight is linked to `SpellBad` color(see `:help :hi-link`). It seems good default value.

```vim
highlight link EnError SpellBad
```

**Comment by kstep** [comment]
I have a syntastic integration in my fork, see [setloclist](https://github.com/kstep/ensime-vim/tree/setloclist) branch. It's still under development, buy you may want to try it out.

**Comment by oschrenk** [comment]
Support for changing this would be great. Right now type check errors make everything unreadable under my current theme

**Comment by oschrenk** [comment]
It seems it actually already landed upstream. I can set `let EnErrorStyle='SpellBad'`, save file and then see changes in the highlighting. 

Can't make it work though having it in my `.vimrc`

**Comment by vito-c** [comment]
There is an ErrorStyle already available via the syntax `*Error          any erroneous construct` `:help syntax` line 258 there should be a way to have that be the default.

**Comment by yazgoo** [comment]
@oschrenk : fixed support for .vimrc override of EnErrorStyle in #133, please re-open if it does not fix it.
