### ISSUE TITLE
global name 'EnsimeLauncher' is not defined

### ISSUE THREAD

**Issue by cb372** [ensime/ensime-vim#52]
* OS X
* Vim 7.4.712
* Python 2.7.6 (OS X default, not Homebrew)
* Scala 2.11.7, sbt 0.13.9

I believe I followed the README correctly:

1. `$ sudo pip install websocket-client`

2. `$ export BROWSER="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`

3. `$ cd code/scalacache`

4. `$ sbt gen-ensime` didn't report any errors.

5. Installed ensime-vim using Pathogen (is this supported?)

6. `$ vim core/src/main/scala/scalacache/package.scala`

Vim spat out what looks like a Python error, but I'm not sure how to debug this further:

```
"core/src/main/scala/scalacache/package.scala" 188L, 7606C
Error detected while processing function ensime#cursor_moved..<SNR>63_call_plugin:
line   14:
E605: Exception not caught: <type 'exceptions.NameError'>:global name 'EnsimeLauncher' is not defined
Press ENTER or type command to continue
```

**Comment by cb372** [comment]
I tried installing the ensime_launcher package (`$ sudo pip install ensime_launcher`) but it didn't help. Still get the same error.

**Comment by todesking** [comment]
Its my mistake! I'm working on it.

**Comment by yazgoo** [comment]
looks like the way EnsimeLauncher is imported is wrong, it should be:

````python
from ensime_launcher import EnsimeLauncher
````

**Comment by yazgoo** [comment]
This should be fixed, please re-open if not.
