### ISSUE TITLE
where does rake come from?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-vim#56]
http://fommil.com/ensime/ensime-vim/38

```
$ bundle exec rake
bundler: command not found: rake
Install missing gem executables with `bundle install`
```

what is the fix for this? I'll add it to the docker image.

**Comment by yazgoo** [comment]
We can remove:
    - bundle install
    - bundle exec rake
As a matter of fact, there is no direct requirement for ruby in ensime-vim.
The only ruby requirement is neo2vim, which is its own project:
https://github.com/yazgoo/neo2vim

**Comment by fommil** [comment]
ok, well we have `bundle` installed in the docker images for you to use in neovim. Let me know if that changes.
