### ISSUE TITLE
How about license?

### ISSUE THREAD

**Issue by todesking** [ensime/ensime-vim#66]
Oh we have no license notation in the repository.

It looks theres no license convention in ensime project(ensime-server is 3BSD, ensime-emacs is GPL, ensime-atom is MIT, etc).  Which should we choose?

**Comment by yazgoo** [comment]
I'd be inclined to choose a permissive license like MIT, but maybe we can put this to a vote, here are some alternatives, feel free to add some:
- GPLv3
- AGPLv3
- MIT
- BSD 3-Clause License

**Comment by yazgoo** [comment]
Ok, let's vote then, I'll be closing the votes on sunday.
My vote:

MIT

**Comment by todesking** [comment]
+1 to MIT :)
