### ISSUE TITLE
EnDeclaration opens new buffer without syntax highlighting

### ISSUE THREAD

**Issue by Jacoby6000** [ensime/ensime-vim#77]
This may very well be my own fault, but the title says it all.

Using [My vimrc](https://github.com/Jacoby6000/my-vimrc/blob/master/.vimrc), running :EnDeclaration creates a new v-split buffer (yay), with no syntax highlighting (no yay) until i :setf scala

**Comment by Jacoby6000** [comment]
This also occurs when I use neovim, if that matters.

**Comment by yazgoo** [comment]
I've just merged #79 for that, does that fixes it on your end ?

**Comment by yazgoo** [comment]
closing please re-open if not fixed.

**Comment by Jacoby6000** [comment]
Confirmed! thanks so much!
