### ISSUE TITLE
Not working in NeoVim

### ISSUE THREAD

**Issue by JD557** [ensime/ensime-vim#94]
Installing this plugin with Pathogen (`git clone https://github.com/ensime/ensime-vim.git` into `.vim/bundle`/`.nvim/bundle`) works on Vim, but seems to fail silently in NeoVim.

If this is a problem with the installation procedure and not with the code, it be nice to add a Pathogen howto in the ReadMe.

**Comment by JD557** [comment]
After some quick tests, this seems to be related to the first lines of `plugin/ensime.vim`, namely:

```
if has('nvim')
  finish
endif
```

Is neovim not supposed to load this file?

**Comment by Jacoby6000** [comment]
I, too, am having this issue. Installed via Plug in neovim, and Vundle in vim. Works in vim, not in neovim.  My vim and neovim installations share the same vimrc, except for the plugin installs.

**Comment by yazgoo** [comment]
Let me explain how the plugin system is supposed to work between nvim and vim.
For nvim, you should just need:
  - rplugin/python/ensime-vim
  - ensime_launcher/__init__.py
Since vim does not support rplugins, @todesking and I designed a tool to convert rplugins to vim normal plugins. They generate:
  - pulgin/ensime.vim
  - autoload/ensime.vim
Which are only necessary for vim (hence the `has('nvim')`).
The problem seems to be that (for example here I'm using plug with `call plug#begin('~/.vim/plugged')`:
~/.vim/plugged/ensime-vim/rplugin/python/ensime.py
Is not loaded anymore.
Doing a `cp -r ~/.vim/plugged/ensime-vim/rplugin/ ~/.config/nvim/` seems to help.
Now we have to figure out why rplugin is not loaded anymore from plugged directory.

**Comment by yazgoo** [comment]
Does the problem still occur ? I can't reproduce it on last commit.

**Comment by JD557** [comment]
It still occurs on my side.

**Comment by yazgoo** [comment]
Could you please give more detail about what you're doing.
Here is what I tried:

```
$ nvim -v | head -1
NVIM v0.1.0-6-ge19f1c5 (compiled Nov  5 2015 13:38:19)
$ curl -LSso ~/.config/nvim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
$ mkdir ~/.config/nvim/bundle
$ cd ~/.config/nvim/bundle/
$ git clone https://github.com/ensime/ensime-vim.git 
$ nvim
:UpdateRemotePlugins
remote/host: python host registered plugins ['ensime.py']
````
Do you get anything at all in .ensime_cache/*.log ?

**Comment by JD557** [comment]
Oops, my bad. I didn't know about `:UpdateRemotePlugins` (I thought that was related to Plug).

Sorry for the confusion. I'll close this issue now.

**Comment by stevendobay** [comment]
I might need a reopen:

```sh
sudo add-apt-repository -y ppa:neovim-ppa/unstable && sudo apt-get update && sudo apt-get install neovim vim-nox-py2 python-pip python-dev python-software-properties && pip2 install websocket-client sexpdata neovim
```
init.vim ->

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'bling/vim-airline'
Plug 'ensime/ensime-vim'
Plug 'derekwyatt/vim-scala' , {'for' : 'scala'}
call plug#end()
```

call 

```vim
:w
:source %
:PlugInstall
:UpdateRemotePlugins # tried to copy the rplugin directory before
```

ensimeConfig and

- [x] works with vim-nox-py2
- [ ] works with neovim(:EnInstall is an unknown command but :h ensime gives the docs)

Ubuntu 16.04, neovim 0.16, +python, -python3
Reproduced: 3 times with two different machines

**Comment by ktonga** [comment]
@stevendobay Have you run `sbt ensimeConfig` on the project? The plugin needs the ensime project descriptor. I'm asking because I can't see it listed in your steps.
Also, open a scala or java file, the plugin starts a server when it detects one of those FTs

**Comment by stevendobay** [comment]
@ktonga ^ "...ensimeConfig and..."(before the checklist, otherwise it wouldn't work with vim-nox-py2)

**Comment by ktonga** [comment]
Ups sorry, didn't see it.
